### ISSUE TITLE
Mineshaft Antechamber Ceiling

### ISSUE THREAD

**Issue by kaojinn** [Brian-Wuest/MC-Prefab#1]
In the bottom chamber created by the mineshaft, the ceiling does not generate.
![exposedmineshaft](https://cloud.githubusercontent.com/assets/20660299/17344793/082badba-58c9-11e6-9c58-7ff6b0e393da.png)

**Comment by Brian-Wuest** [comment]
The mineshaft will create a floor at Y14 with stone to make sure that the chamber doesn't get flooded. The removed blocks will be saved and placed in the chest.

**Comment by Brian-Wuest** [comment]
Fixed in version 1.1.0.8.

Closing
