### ISSUE TITLE
Mod loading but not loading? Crashes when in Mod page and click on Prefab

### ISSUE THREAD

**Issue by Ruffrider86** [Brian-Wuest/MC-Prefab#102]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: 1.14.4-28.0.18
    1. Mod Version: 1.4
1. What type of issue is this? Choose one of the following:
    1. **Bug** 
    
    1. Details:
Minecraft loads up fine. 
Says Mod is loaded. 
Went into world and none of the recipes work.
Backed out to main page and went into MODS
Shows its loaded in forge list but moment you click on the mod name, minecraft crashes 

Below is crash report. Hope it helps fix issue

[crash-2019-08-13_17.31.11-client.txt](https://github.com/Brian-Wuest/MC-Prefab/files/3499008/crash-2019-08-13_17.31.11-client.txt)

**Comment by Brian-Wuest** [comment]
Thank you, I have been able to duplicate it.

The weird thing is that it's not working when playing on installed minecraft but works just fine in development....so yeah.....gonna take a bit to figure out what I did wrong.


Sorry! :(

**Comment by Brian-Wuest** [comment]
I was able to figure out what was wrong and address the defect. This will be fixed with 1.4.0.1 which is being uploaded/reviewed by curseforge right now.

Closing this issue.
