### ISSUE TITLE
New basic starter house has silverfish!

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#103]
Apparently the developer mis-clicked on the creative menu when designing this building and included Stone Brick blocks which contain silverfish!

**Comment by Ruffrider86** [comment]
😂😂😂
House and farm in 1

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.4.0.2 which has been uploaded to CurseForge and will be approved shortly.
