### ISSUE TITLE
[1.14.4] Failed to create mod instance. ModID: prefab, class com.wuest.prefab.Prefab java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: com.wuest.prefab.Proxy.ClientProxy.<init>()void/newInvokeSpecial

### ISSUE THREAD

**Issue by schwabe93** [Brian-Wuest/MC-Prefab#108]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version:   forge-28.0.75
    1. Mod Version: 	prefab-1.4.0.4.jar
What type of issue is this? Choose one of the following:
Bug (Something doesn't work the way you expect or the game crashes/has an issue)
Crash log : [https://pastebin.com/ikQBxHDf](https://pastebin.com/ikQBxHDf)

**Comment by Brian-Wuest** [comment]
Forge changed how they do recipe conditions in a recent build. Going to have to figure it out.

**Comment by Brian-Wuest** [comment]
This issue was introduced in forge build 62 for 1.14.4. I have updated the description of the versioned file and have uploaded Prefab version 1.4.0.5 to address this issue for forge versions 62 and later.

Once this is made available on CurseForge please download and enjoy!

Closing issue
