### ISSUE TITLE
Crash on Loading into World

### ISSUE THREAD

**Issue by IchigoGames** [Brian-Wuest/MC-Prefab#109]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version :1.14.4
    1. Forge Version 28.0.92
    1. Mod Version:prefab-1.4.0.5
1. What type of issue is this? Choose one of the following:
    1. **Bug** Crash on Loading into world singeplayer https://pastebin.com/CzuBDHA8

**Comment by Brian-Wuest** [comment]
Yay,  more beta breaking changes!

I will look into this tonight.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.4.0.6 which has just been uploaded to CurseForge and waiting approval.

Closing this issue.
