### ISSUE TITLE
Starter house shouldn't provide nether materials

### ISSUE THREAD

**Issue by LemADEC** [Brian-Wuest/MC-Prefab#11]
As of prefab-1.1.1.1.jar, the Loft starter house is made of Nether materials which can easily be recycled and bypass the nether requirement (namely: quartz blocks, slabs and stairs into nether quartz).

Please add an option to disable the loft or change it's materials.

**Comment by Brian-Wuest** [comment]
I will add the configuration option and make it so the loft is disabled by default.

Server side configuration will take precedence for what is shown in the GUI.

**Comment by LemADEC** [comment]
sounds good

**Comment by Brian-Wuest** [comment]
This feature has been included in 1.1.1.2 which has been released on curse.
