### ISSUE TITLE
Bug: NoSuchMethodError: net.minecraft.entity.player.PlayerEntity.getPersistantData()

### ISSUE THREAD

**Issue by Austin5003** [Brian-Wuest/MC-Prefab#111]
Occurred when attempting to join a world created before adding prefab.

Minecraft Version: 1.14.4
Forge Version: 28.1.0
Mod Version: 1.4.0.6

[crash-2019-09-12_18.54.23-server.txt](https://github.com/Brian-Wuest/MC-Prefab/files/3607873/crash-2019-09-12_18.54.23-server.txt)

**Comment by Brian-Wuest** [comment]
This is due to reverting something they did not that long ago.

Also; finally a recommended build! Wh00t!

Should have an update later today.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.4.0.7 which has just been uploaded onto curseforge. It should be available shortly.

Closing this issue.

**Comment by Wissi** [comment]
No version  1.4.0.7 yet. 
Been over 2 days.
Can you check and see if it was rejected by Curse or needs to be uploaded again, please?

Thanks.

**Comment by Brian-Wuest** [comment]
It just got approved!

Must have been something you said ;)
