### ISSUE TITLE
1.14.4 [prefab:main_channel] rejected their server side version number

### ISSUE THREAD

**Issue by Wissi** [Brian-Wuest/MC-Prefab#112]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: 28.1.1
    1. Mod Version: prefab-1.4.0.6.jar   (Yes, client/server have same file version)
1. What type of issue is this? Choose one of the following:
    1. **Bug**
1. If this is a **bug**, 

Server will reject client stating:
```
 [prefab:main_channel] rejected their server side version number
```
Full latest.log (for client) [here](https://gist.github.com/Wissi/cbe5bb23082d6268b97ae6961e23744d).

Thanks.

**Comment by Brian-Wuest** [comment]
Closing, that version of the mod doesn't support forge version 28.1.1.

1.4.0.7 has been uploaded to curseforge and is awaiting approval
