### ISSUE TITLE
tick error?

### ISSUE THREAD

**Issue by holla023** [Brian-Wuest/MC-Prefab#113]
Minecraft Version: 1.14.4
forge: 28.1.1
mod: prefab-1.4.0.6.jar

Bug issue where the game gets to 100% loading into a world then crashes and says something about a tick loop.
[crash-2019-09-14_23.34.34-server.txt](https://github.com/Brian-Wuest/MC-Prefab/files/3613461/crash-2019-09-14_23.34.34-server.txt)

**Comment by Brian-Wuest** [comment]
Mod Version 1.4.0.6 is not compatible with forge 28.1.1. A new version has been uploaded to curseforge. They are slow to approve.

Closing.
