### ISSUE TITLE
Inner Seams of Glass Slabs should be invisible

### ISSUE THREAD

**Issue by WenXin20** [Brian-Wuest/MC-Prefab#115]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: v1.14.4
    1. Forge Version: v28.1.65
    1. Mod Version: v1.4.0.7
1. What type of issue is this?:
    1. **Enhancement** 
1. Enhancement Details:
    1. Details: Currently, Glass Slabs display the inner seam when they are placed next to each other, but instead should be invisible similar to Vanilla Minecraft Glass.
    2. This affects double slabs, upper slabs, and lower slabs.
    3. Double Slabs also render incorrectly underwater, and should render similarily to Glass blocks when underwater.
    3. ![2019-10-28_18 09 46](https://user-images.githubusercontent.com/12000593/67724809-46440780-f9ae-11e9-8fee-73de1e1d8cb7.png)

    4. ![2019-10-28_18 19 29](https://user-images.githubusercontent.com/12000593/67725308-e4849d00-f9af-11e9-9b72-ff60ad5bf8f3.png)

**Comment by Brian-Wuest** [comment]
hmm, I will see what I can do with this when I get back into development.

Been taking a break lately.

**Comment by Brian-Wuest** [comment]
I duplicated your first issue, however I cannot duplicate the second one with the water. I am using build 28.1.90.

![2019-11-13_17 23 35](https://user-images.githubusercontent.com/13502068/68813183-abe4f480-063a-11ea-9ac2-bb374237c481.png)

**Comment by WenXin20** [comment]
Oh, in my image I was using a texture pack. The issue I meant was the water flowing down it's sides.

**Comment by Brian-Wuest** [comment]
Ah, got it.

Thank you.

**Comment by WenXin20** [comment]
It looks like Paper Lanterns also have water flowing down it's sides. Waterloggable maybe?

**Comment by Brian-Wuest** [comment]
Yeah, that would work however for the glass slabs it doesn't make sense when it's a double block since it's solid then. By default half-slabs are water loggable and doubles are not. The falling water effect is there because of the transparencies in the block model. Regular glass doesn't have this because it's not water loggable though I have to figure out how it works yet.

**Comment by Brian-Wuest** [comment]
Think I got this working how I want it too.

Had to make it waterlogged in order for it to render nicely. Couldn't get it to render like glass (still don't know why.

In addition to fixing the falling water rendering and the rending of adjacent glass blocks I fixed an issue where it wasn't allowing light to go through the block like glass does. Going to fix the Smart Glass block and the Phasic Block.


![2019-11-14_20 17 45](https://user-images.githubusercontent.com/13502068/68911870-00ac6c00-071c-11ea-829e-015e1f77026b.png)

![2019-11-14_20 18 09](https://user-images.githubusercontent.com/13502068/68911875-0609b680-071c-11ea-8346-5274c831a75b.png)

**Comment by WenXin20** [comment]
Bluepower glass had a similar issue that I reported at Qmunity/BluePower#498, if that helps any.

**Comment by Brian-Wuest** [comment]
Yeah it does. Basically re-implement from the vanilla glass block. Gonna be tricky with that since this is a slab as well. Probably better than the ugly stuff I have locally right now.

Thank you!

**Comment by WenXin20** [comment]
Glad to help!

**Comment by Brian-Wuest** [comment]
After looking at their code it's about the same as what I created, just tweaked a bit.

I will probably push this out next week some time. I have two new buildings I want to get out as well. Just need to talk to my graphics guy 😸

**Comment by WenXin20** [comment]
Nice!

**Comment by Brian-Wuest** [comment]
This has been fixed with the 1.4.0.8 release of prefab which has just been uploaded to CurseForge. This release will become available after their review process has been completed.

**Comment by WenXin20** [comment]
I also recently realized that glass stairs has inner seams rendering as well

**Comment by Brian-Wuest** [comment]
Please create a separate issue for this :)
