### ISSUE TITLE
dedicated/virtual server after placing starter house crashes client after placing(1.14.4-86)

### ISSUE THREAD

**Issue by SDUBZ** [Brian-Wuest/MC-Prefab#116]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: 1.14.4-86
    1. Mod Version: prefab-1.4.0.7
1. What type of issue is this? Choose one of the following:
    1. **Bug** Cant rejoin dedicated/virtual server after placing starter house
also crashes client after placing starter house on server
![2019-11-13_14 43 43](https://user-images.githubusercontent.com/14084377/68731614-c90ec880-0624-11ea-8526-0cac0479513a.png)
![2019-11-13_14 43 55](https://user-images.githubusercontent.com/14084377/68731615-c90ec880-0624-11ea-9ddb-a68f6baec3ce.png)

![image](https://user-images.githubusercontent.com/14084377/68731420-1fc7d280-0624-11ea-82a8-56a8e8ed03d5.png)

Logs:
client:
[debug.log](https://github.com/Brian-Wuest/MC-Prefab/files/3839326/debug.log)
[latest.log](https://github.com/Brian-Wuest/MC-Prefab/files/3839327/latest.log)
server:
[debug.log](https://github.com/Brian-Wuest/MC-Prefab/files/3839330/debug.log)
[latest.log](https://github.com/Brian-Wuest/MC-Prefab/files/3839331/latest.log)

**Comment by SDUBZ** [comment]
okay can rejoin server now not sure what fixed that part but the client crashing needs to be fixed still, but i need to test more dedicated side to see if the joining has been fixed there

**Comment by Brian-Wuest** [comment]
Looked through your logs and I cannot pinpoint an issue coming from Prefab.

You have a TON of errors though about connecting to curseforge or other sites during version checking of various mods (though not mine!).

I can try running a dedicated server tomorrow morning to see if I can duplicate the issue.

**Comment by SDUBZ** [comment]
tested it happens even on my dedicated server too not sure if mod conflict happening

**Comment by Brian-Wuest** [comment]
Verified on development dedicated server which just has Prefab. No error.

I updated local version of forge to 28.1.90 and I don't have many local changes outside of changes to add a new moderate sized house.

This sounds like a mod conflict but from your previously provided logs, I cannot determine which mod would cause the conflict.

If you own dedicated server doesn't have a lot of mods associated with it you could try removing some until the error doesn't happen at all or start with just Prefab and keep adding until it happens again.

**Comment by SDUBZ** [comment]
the only thing i ever saw once the item was placed was inventory sorter but last i checked it didnt do anything with right click

**Comment by Brian-Wuest** [comment]
I'm sorry, without a narrowed down list of mods specifically causing this issue I cannot pinpoint the problem and fix it.

**Comment by Brian-Wuest** [comment]
There has been no addition information provided as requested. When the information is provided this issue can be reopened.

Closing issue.
