### ISSUE TITLE
1.12.2 bug no prefab tab or items available in creative nor do i spawn with them

### ISSUE THREAD

**Issue by PItlosTails** [Brian-Wuest/MC-Prefab#117]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.12.2
    1. Forge Version: forge-14.23.5.2847
    1. Mod Version: newest as of (24.11.2019)
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
   
1. Details:
none to provide other than items being gone

**Comment by Brian-Wuest** [comment]
Please provide screen shots. Also a few things to note:

- Prefab doesn't have a specific tab for it's blueprints. They all fall under Misc.
- Check your configuration to see if you accidentally disabled the features of the mod.
- If everything is set up correctly, check that you didn't accidentally set forge up to use the "global" configuration file. Check the forge configuration for this flag.

Log files also help

**Comment by Brian-Wuest** [comment]
Closing this since there has been no updates for 2 weeks. If this issue comes up again please provide the information requested.
