### ISSUE TITLE
Inner Seams of Glass Stairs also should be invisible

### ISSUE THREAD

**Issue by WenXin20** [Brian-Wuest/MC-Prefab#118]
1. **What version of Minecraft, Forge, and Prefab are you running?**
    1. Minecraft Version: v1.14.4
    1. Forge Version: v28.1.65
     1. Mod Version: v1.4.0.7
1. **What type of issue is this?:**
  - **Bug**

3. **Details:** 
- Currently, Glass Stairs display the inner seam when they are placed next to each other, but instead should be invisible similar to Vanilla Minecraft Glass.

**Comment by WenXin20** [comment]
As requested :)

**Comment by Brian-Wuest** [comment]
Saw this a while a go but never got around too it, sorry!

Will be working on this soon.

**Comment by Brian-Wuest** [comment]
Here are some screen shots.

I got it to not show at least the bottom seam for the other "glass" blocks by using forge tags. This means that it will show this way for other mods that use the same tag.

I am also going to get this to work for Glass Slabs too!

![2020-01-13_18 22 53](https://user-images.githubusercontent.com/13502068/72303212-18c43d00-3632-11ea-9821-41a10ea9a22c.png)

![2020-01-13_18 23 24](https://user-images.githubusercontent.com/13502068/72303216-1c57c400-3632-11ea-98f2-97f138dcaf12.png)

![2020-01-13_18 24 07](https://user-images.githubusercontent.com/13502068/72303223-1eba1e00-3632-11ea-927c-d8d1e668d43f.png)

**Comment by Brian-Wuest** [comment]
Here's the side being invisible appropriately
![2020-01-13_18 34 58](https://user-images.githubusercontent.com/13502068/72303678-a5232f80-3633-11ea-9c0a-1cb6da669712.png)
 for a double-stacked glass slab.

**Comment by Brian-Wuest** [comment]
I plan on releasing a version with these changes Wednesday unless you have any concerns.

**Comment by WenXin20** [comment]
Nice!

**Comment by Brian-Wuest** [comment]
Ha, wasn't expecting a response today. Going to create a build and push to CurseForge. Thank you for helping make the mod better!

**Comment by Brian-Wuest** [comment]
This has been fixed with 1.4.0.9 and has been approved/released on CurseForge.

Closing issue.
