### ISSUE TITLE
[1.14.4] Crash issue with OpenJDK

### ISSUE THREAD

**Issue by AzureDoom** [Brian-Wuest/MC-Prefab#119]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: 1.14.4-28.1.107
    1. Mod Version 1.4.0.8
1. What type of issue is this? Choose one of the following:
    **Bug** When right clicking it will crash the game. https://gist.github.com/AzureDoom/0c8ab101dc01eea11e95deae6c07f8f8

Suggested Fix: https://gist.github.com/androidfred/bc64da9e6a355b984d37439ed63ae16b

**Comment by Brian-Wuest** [comment]
I will not be supporting OpenJDK. Create an Oracle account (It's free!) and download the appropriate version of the JDK like everyone else.

Minecraft is built on the official JDK provided by Oracle same as most of the other mods so you would probably have issues with other mods (and possibly the game!) outside of just mine.

Closing issue.
