### ISSUE TITLE
Basic House hasn't got a crafting table

### ISSUE THREAD

**Issue by STOKE-STER** [Brian-Wuest/MC-Prefab#124]
What version of Minecraft, Forge and Mod are you running?
   Minecraft Version:1.15.2
   Forge Version:31.1.1
   Mod Version:1.5.0.0
What type of issue is this? Choose one of the following: **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)

One of the new starter houses has an option to include a crafting table, but once the house is built it has 2 furnaces, 6 double chests and 0 crafting tables.

![2020-02-12_02 44 22](https://user-images.githubusercontent.com/36657224/74258528-31636800-4d42-11ea-93da-5d701479d307.png)

**Comment by Brian-Wuest** [comment]
Make sure that the mod config file isn't set up to exclude the crafting table during structure generation.

**Comment by STOKE-STER** [comment]
It's not, all the other houses I built with your mod had crafting tables :)

**Comment by Brian-Wuest** [comment]
k, I will take a look at this when I get back from work today.

**Comment by Brian-Wuest** [comment]
Weird, looks like the crafting table isn't in my scan. I can re-scan and put that in the next release.

I am waiting on my graphics artist to create new icons for the windmill and town hall items and then I can release this fix as well as others. 

Thank you for finding this!

**Comment by STOKE-STER** [comment]
No problem :) 

Love the mod!

**Comment by Brian-Wuest** [comment]
This has been updated with version 1.4.0.10 and 1.5.0.1. Currently waiting on approval for 1.4.0.10 from curseforge before uploading the next one. Closing this issue.
