### ISSUE TITLE
Starter house chest contents not loading 

### ISSUE THREAD

**Issue by niceassassin** [Brian-Wuest/MC-Prefab#126]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version:1 1.15.2
    1. Forge Version: 31.1.17
    1. Mod Version: 1.5.0.0
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)

When Loading the starter house the starter chest contents are not loading in the chests. 
they are all set to true in the config

**Comment by Brian-Wuest** [comment]
This has been fixed and is awaiting approval from CurseForge.

This will be in version 1.5.0.1 for MC version 1.15.2.

**Comment by Brian-Wuest** [comment]
This has been released on CurseForge.

Closing Issue

**Comment by niceassassin** [comment]
Thanks Brian
