### ISSUE TITLE
Buildings wont build

### ISSUE THREAD

**Issue by davidml1023** [Brian-Wuest/MC-Prefab#128]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.15.2
    1. Forge Version: 31.1.0
    1. Mod Version: 1.5.0.1
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)

Everything else seems to work. Compressed stone and bundles of timber can be crafted. New blueprints can be crafted. Build previews can be seen. It shows the text "right click on any block in the world to remove the preview" when previewing. The only problem is that when I click to actually build, nothing happens - not even a text. Nothing seems out of the ordinary with the config file. Kinda weird.

*Edit: This happens no matter what type of map or mode I use. I've tested to see if cheats on/off affect it, survival, creative, adventure, flat, default, etc. all the same.

**Comment by Brian-Wuest** [comment]
I made a sample modpack with the Twitch app and it works fine. I did use the latest version of forge and it looks like you are using an older version of forge. Please update to the latest release and try again.

**Comment by davidml1023** [comment]
That did it. The forge version I was using was the recommended version but it works with latest. Thank you.
