### ISSUE TITLE
[1.15.2] Feature request- config option to disable drops from bulldozer.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#129]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.15.2

As a pack author I would love to be able to allow the bulldozer for clearing land, but disable it for mining, the Project E repair talisman repairs the bulldozer, making it a super cheap cheaty way to mass mine.

**Comment by Brian-Wuest** [comment]
Hmmm, great idea!

**Comment by Brian-Wuest** [comment]
This has been released with 1.4.0.12 and 1.5.0.2.

**Note**: The 1.5.0.2 version is currently going through the CurseForge approval process and will be available for download once it is approved.

Closing issue.
