### ISSUE TITLE
Hobbit hole house bed issue

### ISSUE THREAD

**Issue by iPencil** [Brian-Wuest/MC-Prefab#13]
Just a quick and easy fixable issue:

In the hobbit hole the bed has no valid spawn point because its surrounded by half blocks:
http://i.imgur.com/7xavDDr.png

When you die or use /home it cant find a valid location and you get "Bed not found" .

Easily fixable by making the 2 blocks next to it full sized blocks:

http://i.imgur.com/s1ekbSQ.png

**Comment by Brian-Wuest** [comment]
Hi, thanks for finding that! We are getting to our old schedule of releases as we have additional structures we will be providing. So a fix for this issue will be in next Monday's release. (10/10/2016)

**Comment by iPencil** [comment]
Alright, this isn't a big issue, sounds great! :)

**Comment by Brian-Wuest** [comment]
This issues has been fixed with version 1.1.1.4 which is now available on curseforge.
