### ISSUE TITLE
Failure to initialize crash

### ISSUE THREAD

**Issue by Lordbaane** [Brian-Wuest/MC-Prefab#132]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.15.2
    1. Forge Version: 31.127
    1. Mod Version:1.5.0.2

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 3/25/20 1:29 PM
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Prefab (prefab) has failed to load correctly
§7class com.wuest.prefab.Blocks.BlockPaperLantern overrides final method func_200124_e.(Lnet/minecraft/block/BlockState;)Z
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:altius_world/MixinMinecraftServer_A,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins.json:MixinMinecraftServer,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_ma.json:MixinMinecraftServer_MA,pl:mixin:A,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: FreeBSD (amd64) version 11.2-STABLE
	Java Version: 1.8.0_232, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2075911536 bytes (1979 MB) / 5530189824 bytes (5274 MB) up to 11454644224 bytes (10924 MB)
	CPUs: 24
	JVM Flags: 2 total; -Xmx12288M -Xms2048M
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.1.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.1.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.27
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		torchslabmod-1.15.1_v1.5 (1).jar Torch Slab Mod {torchslabmod@1.5.0 CREATE_REGISTRIES}
		NetherPortalFix_1.15.2-6.0.0.jar NetherPortalFix {netherportalfix@6.0.0 CREATE_REGISTRIES}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 CREATE_REGISTRIES}
		mining-helmet-1.15.2-1.0.7.jar Mining Helmet {mining_helmet@1.0.7 CREATE_REGISTRIES}
		craftingstation-3.1.0.jar Crafting Station {craftingstation@3.1.0 CREATE_REGISTRIES}
		AdvancedSkinCustomization-2.8.2.jar Advanced Skin Customization {advskinmod@2.8.2 CREATE_REGISTRIES}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 CREATE_REGISTRIES}
		vanillathings-1.15.2-0.5.7.jar Vanilla Things {vanillathings@0.5.7 CREATE_REGISTRIES}
		prefab-1.5.0.2.jar Prefab {prefab@1.4.0.12 ERROR}
		AttributeFix-1.15.2-7.0.1.jar AttributeFix {attributefix@7.0.1 CREATE_REGISTRIES}
		no-nitwits-1.15.2-1.0.0.jar No Nitwits {no_nitwits@1.0.0 CREATE_REGISTRIES}
		extrabows-v1.15.2+b1.jar Extra Bows {extrabows@v1.15.2 b1 CREATE_REGISTRIES}
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar Macaw's Windows {mcwwindows@1.0.0 CREATE_REGISTRIES}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 CREATE_REGISTRIES}
		colytra-FORGE-1.15.2-3.0.jar Colytra {colytra@FORGE-1.15.2-3.0 CREATE_REGISTRIES}
		invtweaks-1.15.2-1.0.2.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.2 CREATE_REGISTRIES}
		BowInfinityFix-1.15.2-rv8.jar Bow Infinity Fix {bowinfinityfix@rv8 CREATE_REGISTRIES}
		Waystones_1.15.2-6.0.1.jar Waystones {waystones@6.0.1 CREATE_REGISTRIES}
		ForgeEndertech-1.15.2-6.0.1.0-build.0011.jar Forge Endertech {forgeendertech@6.0.1.0 CREATE_REGISTRIES}
		AdFinders-1.15.2-4.0.2.0-build.0012.jar Advanced Finders {adfinders@4.0.2.0 CREATE_REGISTRIES}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 CREATE_REGISTRIES}
		RingOfRepair-1.15.2-1.1.19.jar Ring of Repair {ring_of_repair@1.1.19 CREATE_REGISTRIES}
		JRFTL+[1.15.2]-1.1.jar JRFTL {jrftl@1.1 CREATE_REGISTRIES}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 CREATE_REGISTRIES}
		CookingForBlockheads_1.15.2-8.0.1.jar Cooking for Blockheads {cookingforblockheads@8.0.1 CREATE_REGISTRIES}
		VanillaTweaks-1.15.2.1.5.18.jar VanillaTweaks {vanillatweaks@1.15.2.1.5.18 CREATE_REGISTRIES}
		DungeonCrawl-1.15.2-1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 CREATE_REGISTRIES}
		RingOfTeleport-1.15.2-1.1.19.jar Ring of Teleport {ring_of_teleport@1.1.19 CREATE_REGISTRIES}
		guardvillagers-1.15.2-1.0.6.jar Guard Villagers {guardvillagers@1.0.6 CREATE_REGISTRIES}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 CREATE_REGISTRIES}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version CREATE_REGISTRIES}
		SnowRealMagic-1.15.2-1.7.2.jar Snow! Real Magic! {snowrealmagic@1.7.2 CREATE_REGISTRIES}
		Kiwi-1.15.2-2.7.0.jar Kiwi {kiwi@2.7.0 CREATE_REGISTRIES}
		immersive-portals-0.8(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.8 CREATE_REGISTRIES}
		swampexpansion-1.15.2-1.5.jar Swamp Expansion {swampexpansion@NONE CREATE_REGISTRIES}
		strongfarmland-1.15.2-1.0.0.jar Stronger Farmland Mod {strongfarmland@1.15.2-1.0.0 CREATE_REGISTRIES}
		forge-1.15.2-31.1.27-universal.jar Forge {forge@31.1.27 CREATE_REGISTRIES}
		NoIncreasingRepairCost-1.15.2-1.0.0.jar No Increasing Repair Cost {noincreasingrepaircost@NONE CREATE_REGISTRIES}
		corpse-1.15.2-1.0.3.jar Corpse {corpse@1.15.2-1.0.3 CREATE_REGISTRIES}
		anviltweaks-2.2a.jar Anvil Tweaks {anviltweaks@2.2a CREATE_REGISTRIES}
		forge-1.15.2-31.1.27-server.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		logprot-1.15.1-1.2.jar Logprot {logprot@1.2 CREATE_REGISTRIES}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 CREATE_REGISTRIES}
		repurposedstructures-1.15.2-1.2.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.2.2 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.15.2-2.0.3.jar EnchantmentDescriptions {enchdesc@2.0.3 CREATE_REGISTRIES}
		crocmod-1.15.2-1.5.1-8.jar Crocodile Mod {crocmod@1.15.2-1.5.1-8 CREATE_REGISTRIES}
		EasySteel-1.15.2-1.1.59.jar Easy Steel & More {easy_steel@1.1.59 CREATE_REGISTRIES}
		useful_railroads-1.15.2-1.3.2.21.jar Useful Railroads {usefulrailroads@1.3.2.21 CREATE_REGISTRIES}
		valhelsia_structures-15.0.2a.jar Valhelsia Structures {valhelsia_structures@15.0.2a CREATE_REGISTRIES}
		ironfurnaces-1.15.2-2.0.1.jar Iron Furnaces {ironfurnaces@2.0.1 CREATE_REGISTRIES}
		theplopper-1.15.1-v1.3.jar The Plopper {theplopper@v1.3 CREATE_REGISTRIES}
		RaysDongles-4.2.2b.jar Ray's Dongles {slurpiesdongles@4.2.2b CREATE_REGISTRIES}
		extragolems-10.1.0.jar Extra Golems {golems@10.1.0 CREATE_REGISTRIES}
		dimdungeons-1.05-forge-1.15.2.jar Dimensional Dungeons {dimdungeons@1.15.2-1.05 CREATE_REGISTRIES}
		randomenchants-3.1.0.jar Random Enchants {randomenchants@3.1.0 CREATE_REGISTRIES}
		Craftable+Saddles+[1.15.2]-1.3.jar Craftable Saddles {craftable_saddles@1.3 CREATE_REGISTRIES}
		curios-FORGE-1.15.2-2.0.1.jar Curios API {curios@FORGE-1.15.2-2.0.1 CREATE_REGISTRIES}
		corail_woodcutter-1.1.1-1.15.2.jar Corail Woodcutter {corail_woodcutter@1.1.1 CREATE_REGISTRIES}
		OverpoweredMending-1.15.2-2.0.0+11.jar Overpowered Mending {overpowered_mending@2.0.0+11 CREATE_REGISTRIES}
		extratags-1.0.jar Extra Tags {extratags@1.0 CREATE_REGISTRIES}
		lava-monster-1.15.2-1.0.3.jar Lava Monster {lava_monster@1.0.3 CREATE_REGISTRIES}
		corail_recycler-4.0.3-1.15.2.jar Corail Recycler {corail_recycler@4.0.3 CREATE_REGISTRIES}
		DoubleSlabs-1.15-2.0.3.jar Double Slabs {doubleslabs@2.0.3 CREATE_REGISTRIES}
		additionalevents-1.0a.jar Additional Events {additionalevents@1.0a CREATE_REGISTRIES}
		vanillahammers-1.15.1-1.0.jar Vanilla Hammers {vanillahammers@1.15.1-1.0 CREATE_REGISTRIES}
		harvest-1.15.2-1.0.1.jar Harvest {harvest@1.0.1 CREATE_REGISTRIES}
		expandedstorage-1.1.8+1.15.2.jar Expanded Storage {expandedstorage@1.1.8+1.15.2 CREATE_REGISTRIES}
		PowderPower-1.15.2-3.1.47.jar Powder Power {powder_power@3.1.47 CREATE_REGISTRIES}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 CREATE_REGISTRIES}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 CREATE_REGISTRIES}
		mcw-furniture-1.0.1-mc1.15.1+1.15.2.jar Macaw's Furnitures {mcwfurnitures@1.0.1 CREATE_REGISTRIES}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 CREATE_REGISTRIES}
		Zmod+1.15.2-1.05.jar ZmodSkills {zmod@1.04 CREATE_REGISTRIES}
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 {aquaculture@1.15.2-2.0.13 CREATE_REGISTRIES}
		tramplestopper-1.15.2-2.0.0.1-universal.jar Trample Stopper {tramplestopper@1.15.2-2.0.0.1-universal CREATE_REGISTRIES}
		betterbedrockgenerator-1.15.2-0.0.6.jar Better Bedrock Generator {betterbedrockgenerator@0.0.6 CREATE_REGISTRIES}
		FastLeafDecay-v20.jar FastLeafDecay {fastleafdecay@v20 CREATE_REGISTRIES}
		Disenchanting_(forge)_1.15.2-1.2.0.jar Disenchanting {disenchanting@1.2.0 CREATE_REGISTRIES}
		leavesdecayonotherleaves-1.1.jar Leaves Decay on other Leaves {leavesdecayonotherleaves@1.1 CREATE_REGISTRIES}
		lootbagmod-1.15.1-1.5.1.jar Loot Bag Mod {lootbagmod@1.15.1-1.5.1 CREATE_REGISTRIES}
		Cyclic-1.15.2-0.2.0.jar Cyclic {cyclic@1.15.2-0.2.0 CREATE_REGISTRIES}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Brian-Wuest** [comment]
Looks like you are playing on a server and the server didn't update the file to the 1.15.2 version of the file. I do not get this error when playing on single player in a modpack.

**Comment by Lordbaane** [comment]
The same file crashed on loading as well on my personal computer. Both wouldn't load, the moment I returned to prior version it worked fine.

**Comment by Brian-Wuest** [comment]
The error shown above "class com.wuest.prefab.Blocks.BlockPaperLantern overrides final method func_200124_e". That method being referenced doesn't even exist in my distributed file or the code.

Below is a screen shot from minecraft for the working 1.15.2 version of the file. Make sure it matches.

![image](https://user-images.githubusercontent.com/13502068/77642596-eab18200-6f2b-11ea-9a4b-73966c8b0932.png)


Also; here is the code for the 1.15.2 version of the offending block: https://github.com/Brian-Wuest/MC-Prefab/blob/master/src/main/java/com/wuest/prefab/Blocks/BlockPaperLantern.java

And here is the 1.14.4 version: https://github.com/Brian-Wuest/MC-Prefab/blob/MC-1.14.4/src/main/java/com/wuest/prefab/Blocks/BlockPaperLantern.java

As you can see the 1.14.4 version does have the offending method (it's the "isSolid" method) but the 1.15.2 version does not.

I even examined the file which got downloaded from curseforge and verified that it matches what I built locally so I didn't upload the wrong version.

**Comment by Lordbaane** [comment]
Could it be a conflict with another mod then? Upon closer inspection with the second crash report it mentions the following:
java.lang.NullPointerException: Initializing game
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.blay09.mods.cookingforblockheads.client.TileEntityRenderers.initBlockColors(TileEntityRenderers.java:36) ~[?:8.0.1] {re:classloading}

**Comment by Brian-Wuest** [comment]
hmmm, nope. I was able to add CookingForBlockheads to my test twitch modpack and load a single player game without issue.

Can you send me your full mod-list so I can test this out on my machine?

**Comment by Lordbaane** [comment]
Mod List: 
		torchslabmod-1.15.1_v1.5 (1).jar 
		damage_indicator-0.1.0.jar 
		mining-helmet-1.15.2-1.0.7.jar 
		craftingstation-3.1.0.jar 
		AdvancedSkinCustomization-2.8.2.jar 
		jei-1.15.2-6.0.0.2.jar
		vanillathings-1.15.2-0.5.7.jar
		prefab-1.5.0.2.jar 
		AttributeFix-1.15.2-7.0.1.jar 
		no-nitwits-1.15.2-1.0.0.jar
		extrabows-v1.15.2+b1.jar
		mcw-windows-1.0.0-mc1.15.1_1.15.2.jar 
		caelus-FORGE-1.15.2-2.0-beta1.jar 
		colytra-FORGE-1.15.2-3.0.jar Colytra 
		invtweaks-1.15.2-1.0.2.jar
		BowInfinityFix-1.15.2
		Waystones_1.15.2-6.0.1.jar
		ForgeEndertech-1.15.2-6.0.1.0-build.0011.jar 
		AdFinders-1.15.2-4.0.2.0-build.0012.jar 
		Clumps-5.0.2.jar 
		RingOfRepair-1.15.2-1.1.19.jar 
		JRFTL+[1.15.2]-1.1.jar 
		journeymap-1.15.2-5.7.0beta1.jar 
		CookingForBlockheads_1.15.2-8.0.1.jar 
		VanillaTweaks-1.15.2.1.5.18.jar
		DungeonCrawl-1.15.2-1.6.3.jar 
		RingOfTeleport-1.15.2-1.1.19.jar 
		guardvillagers-1.15.2-1.0.6.jar 
		u_team_core-1.15.2-2.11.0.156.jar
		Hwyla-forge-1.10.8-B72_1.15.2.jar 
		SnowRealMagic-1.15.2-1.7.2.jar 
		Kiwi-1.15.2-2.7.0.jar Kiwi
		immersive-portals-0.8(forMc1.15withForge).jar 
		swampexpansion-1.15.2-1.5.jar
		strongfarmland-1.15.2-1.0.0.jar 
		forge-1.15.2-31.1.27-universal.jar
		NoIncreasingRepairCost-1.15.2-1.0.0.jar 
		corpse-1.15.2-1.0.3.jar
		anviltweaks-2.2a.jar 
		mcw-bridges-1.0.4fix-mc1.15.2.jar
		useful_backpacks-1.15.2-1.9.4.63.jar 
		repurposedstructures-1.15.2-1.2.2.jar
		EnchantmentDescriptions-1.15.2-2.0.3.jar 
		crocmod-1.15.2-1.5.1-8.jar 
		EasySteel-1.15.2-1.1.59.jar 
		useful_railroads-1.15.2-1.3.2.21.jar
		valhelsia_structures-15.0.2a.jar
		ironfurnaces-1.15.2-2.0.1.jar
		theplopper-1.15.1-v1.3.jar 
		RaysDongles-4.2.2b.jar 
		extragolems-10.1.0.jar 
		dimdungeons-1.05-forge-1.15.2.jar 
		randomenchants-3.1.0.jar 
		Craftable+Saddles+[1.15.2]-1.3.jar
		curios-FORGE-1.15.2-2.0.1.jar 
		corail_woodcutter-1.1.1-1.15.2.jar 
		OverpoweredMending-1.15.2-2.0.0+11.jar 
		extratags-1.0.jar 
		lava-monster-1.15.2-1.0.3.jar 
		corail_recycler-4.0.3-1.15.2.jar
		DoubleSlabs-1.15-2.0.3.jar 
		additionalevents-1.0a.jar 
		vanillahammers-1.15.1-1.0.jar 
		harvest-1.15.2-1.0.1.jar 
		expandedstorage-1.1.8+1.15.2.jar 
		PowderPower-1.15.2-3.1.47.jar 
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar 
		curiouselytra-FORGE-1.15.2-2.0.jar
		mcw-furniture-1.0.1-mc1.15.1+1.15.2.jar 
		globalxp-1.15.2-v1.4.11.jar 
		Zmod+1.15.2-1.05.jar
		Aquaculture-1.15.2-2.0.13.jar Aquaculture 2 
		tramplestopper-1.15.2-2.0.0.1-universal.jar
		betterbedrockgenerator-1.15.2-0.0.6.jar 
		Disenchanting_(forge)_1.15.2-1.2.0.jar 
		lootbagmod-1.15.1-1.5.1.jar
		Cyclic-1.15.2-0.2.0.jar 
	Launched Version: 1.15.2-forge-31.1.27
Hopefully this can shed some light on the issue.

**Comment by Brian-Wuest** [comment]
Pretty sure I got everything and then some.

![image](https://user-images.githubusercontent.com/13502068/77717347-33aa1a80-6fae-11ea-88ff-ba776fd4840d.png)


Got into the game without problem

![image](https://user-images.githubusercontent.com/13502068/77717380-4c1a3500-6fae-11ea-8594-d7e50c4c3faf.png)

**Comment by Lordbaane** [comment]
Maybe it has to do with Forge. I fresh install may fix the issue then. On a side note, what modpack are you using?

**Comment by Brian-Wuest** [comment]
No mod-pack specifically just a boat load of mods. Most of those came from another person experiencing an issue and I got their modlist and added it to mine.

**Comment by Lordbaane** [comment]
Okay, I will close the issue. Hopefully it will be fine. Thanks.
