### ISSUE TITLE
[1.15.2]The glass staircase is not transparent

### ISSUE THREAD

**Issue by EnterFor** [Brian-Wuest/MC-Prefab#133]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version:1.15.2
    1. Forge Version:31.1.27
    1. Mod Version:1.5.0.2
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
    1. Details:
![image](https://user-images.githubusercontent.com/10114685/77732802-9ea43180-7040-11ea-9578-5972b5ea9c68.png)

**Comment by Brian-Wuest** [comment]
You must have a mod conflict with it. In my sample twitch modpack it works just fine.

![image](https://user-images.githubusercontent.com/13502068/77751234-4a269500-6ff3-11ea-8972-a3126631de3f.png)

Here is my modlist, can you look through this and tell me which ones you have that are different and I can add them to my modpack and see what ones could be causing the conflict?

![image](https://user-images.githubusercontent.com/13502068/77751355-89ed7c80-6ff3-11ea-9557-51a53dd58332.png)

**Comment by EnterFor** [comment]
Thank you for your reply. I will investigate and send the result to you. It may take some time!

**Comment by EnterFor** [comment]
I can't find the reason...

**Comment by EnterFor** [comment]
![image](https://user-images.githubusercontent.com/10114685/77828087-7d346a00-7154-11ea-919e-d0335de5eabb.png)
Here's my list of mods, hoping to give some clues

**Comment by Brian-Wuest** [comment]
Apparently I need to look at my own screen shots better. I was able to duplicate the issue. I was apparently showing Glass Stairs from Vanilla Things. Sorry about that!


I was able to duplicate the issue. I can take a look and see what I can do to fix the issue!

Thank you for your patience.

**Comment by Brian-Wuest** [comment]
This has been released with version 1.5.0.3 which has been uploaded to CurseForge and is awaiting their approval.

Closing issue.
