### ISSUE TITLE
**Bug** Minecraft Version: 1.12.2, Forge Version: 14.23.5.2847, Mod Version: 1.3.0.26: NoSuchMethodError

### ISSUE THREAD

**Issue by ReallySadWolf** [Brian-Wuest/MC-Prefab#135]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.12.2
    1. Forge Version: 14.23.5.2847
    1. Mod Version: 1.3.0.26
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game 
Details:
Crashes at Initiializing Minecraft Engine - Rendering Setup - Loading Entity render
with the follow crash (got with VanillaFix, which also identifies Prefab and ChineseWorkshop as potential causes): https://paste.dimdev.org/donigawipu.mccrash

**Comment by Brian-Wuest** [comment]
Minecraft version 1.12.2 is no longer supported as stated on the mod page on CurseForge.

Please update to a modern version of Minecraft.

Closing issue.
