### ISSUE TITLE
Bug config option for starting with homes not working.

### ISSUE THREAD

**Issue by IchigoGames** [Brian-Wuest/MC-Prefab#137]
1. Minecraft Version:1.15.2
    1. Forge Version:31.1.36 and 43
    1. Mod Version:prefab-1.5.0.3
    1. Details: leaving the starting house section of the config blank thats meant to keep players from starting with house does not work on server or single player even with but server and client configs changed.

**Comment by Brian-Wuest** [comment]
I always keep on forgetting this.

Set the configuration this way:
"Starting Item" = "Nothing"

Tested this out and it works fine.
Closing issue.

**Comment by IchigoGames** [comment]
yap that worked ty
