### ISSUE TITLE
Feature Request: Disabling Starter Item.

### ISSUE THREAD

**Issue by AzureDoom** [Brian-Wuest/MC-Prefab#140]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.15.2
    1. Forge Version: Forge-31.1.60
    1. Mod Version: 1.5.0.5
1. What type of issue is this? Choose one of the following:
    1. **Enhancement**
Being able to disable the Starting Item, allowing only crafting of the Prefabs. 

Suggested config
```toml
#Determines if a player receives a starting item on first world join. Server configuration overrides client.
	"Enable Starting Item" = true
```

**Comment by Brian-Wuest** [comment]
The existing configuration option can already do this.

#Determines which starting item a player gets on first world join. Server configuration overrides client.
"Starting Item" = "Nothing"

Closing issue.

**Comment by AzureDoom** [comment]
Oh i was not aware of this, i still adding it into the config comment for Starting Item.

**Comment by Brian-Wuest** [comment]
Yeap; I can add that :)
