### ISSUE TITLE
Crash when using starter house prefab

### ISSUE THREAD

**Issue by CubicBerserker** [Brian-Wuest/MC-Prefab#141]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.15.2
    1. Forge Version: forge-31.1.49
    1. Mod Version: 1.5.0.6
1. What type of issue is this? Choose one of the following:
    1. **Bug**
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

Game crashes when attempting to use the starter house prefab: https://pastebin.com/RERyUmYS
This only started happening after updating to the latest version of Prefab, it was fine before that.

**Comment by slovke** [comment]
Same here 1.14.4 minecraft  with prefab-1.4.0.16 if crashes when i click right click instantly even in new worlds previous version prefab-1.4.0.15 working normal and no crashes so its issue with new release from some reason

**Comment by Brian-Wuest** [comment]
Sigh, no good deed goes unpunished. I even tested some generation. I will look into this immediately.

**Comment by Brian-Wuest** [comment]
Fixes have been uploaded to curse forge. Closing issue.

Again; thank you for reporting this issue and I am sorry that you had too!
