### ISSUE TITLE
Preview Crash

### ISSUE THREAD

**Issue by AzureDoom** [Brian-Wuest/MC-Prefab#143]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version:1.15.2
    1. Forge Version:31.1.74
    1. Mod Version: 1.5.0.7
1. What type of issue is this? Choose one of the following:
    1. **Bug** 
1. Press Preview and crash. Crashlog: https://gist.github.com/AzureDoom/ae0f78d98880f2febf33683c2f759043

**Comment by Brian-Wuest** [comment]
Razelfrazen...why.....I thought I fixed that! 

Thank you. I will get a fix out for that tonight.

**Comment by Brian-Wuest** [comment]
This has been fixed with 1.5.0.8 which has been pushed to curse forge for approval.

**Comment by AzureDoom** [comment]
Yup fixed the issue! Thanks again for supporting us AdaptOpenJDK users!
