### ISSUE TITLE
Infested bricks in basic starting house

### ISSUE THREAD

**Issue by WindFox** [Brian-Wuest/MC-Prefab#144]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.15.2
    1. Forge Version: 31.1.41 (Also tested on 31.1.77)
    1. Mod Version: 1.5.0.8

1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)

1. There are infested bricks in the basic style starting house. I did manage to find some by the back wall next to the torches, but there may be more.

![2020-05-10_13 14 50](https://user-images.githubusercontent.com/3812388/81505838-4c516400-92c0-11ea-9c57-499934da12eb.png)

**Comment by WindFox** [comment]
Using a resource pack to easily see infested stone, I found this in the new basic house:

The back
![2020-05-10_14 45 08](https://user-images.githubusercontent.com/3812388/81507861-2af77480-92ce-11ea-9238-db481e124d5c.png)

One on the front
![2020-05-10_14 45 22](https://user-images.githubusercontent.com/3812388/81507868-38146380-92ce-11ea-89cd-1caf8fc38d2e.png)

Also, some in the Welcome Center
![2020-05-10_14 48 43](https://user-images.githubusercontent.com/3812388/81507875-4498bc00-92ce-11ea-9e55-22e114822e14.png)

**Comment by Brian-Wuest** [comment]
Thanks for reporting this. I could have sworn that I go all of that out of the basic starting house. Didn't even know we had some with the Welcome Center.

What resource pack did you use to see all of that? I want to double check some of the other buildings.

**Comment by WindFox** [comment]
https://www.planetminecraft.com/texture-pack/infested-stone/

I went through some of the buildings that were not in 1.12 and I didn't see anything. But, it was a quick look too.

**Comment by Brian-Wuest** [comment]
Thanks for that! I have a world which has all of the structures in it so I can re-scan them if I want to change something in them :).

**Comment by Brian-Wuest** [comment]
This has been fixed with 1.4.0.18 and 1.5.0.9 for MC versions 1.14.4 and 1.15.2 respectively.

These will be available on curseforge once it gets through their review process.
