### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ekoman93** [Brian-Wuest/MC-Prefab#146]
is there a discord for this mod and is there a way to change the prefabs them selves OR add my own prefab?

**Comment by Brian-Wuest** [comment]
There is no discord server for this mod at this time. I don't have a mechanism to change the existing prefabs either. If you want to contribute to the mod you can, there is a section out on the curseforge site describing how to do that (link is below). Though it would be contributing for everyone not just for your own server.

https://www.curseforge.com/minecraft/mc-mods/prefab

**Comment by Brian-Wuest** [comment]
Closing as there has been no further discussion after two weeks.
