### ISSUE TITLE
[Suggestions]

### ISSUE THREAD

**Issue by BedrockLegends** [Brian-Wuest/MC-Prefab#148]
Lake house
Some kind of Boat house
Maybe a Boat for people who love to live in the water
Dock
Lighthouse
Basketball Court 
Sugar Cane Farm

**Comment by Brian-Wuest** [comment]
I like these ideas.

For the dock, we have something similar already. Have you taken a look at the Fish Pond?

**Comment by brisingraerowing** [comment]
I would say the dock would be used like a bridge with only one end on land, for putting into a lake / ocean.

**Comment by Brian-Wuest** [comment]
@BrisingrAerowing The Instant bridge can be used like this already, it's smallest size is currently 25 blocks which may be too large for a dock, maybe bring that down to like 8?

**Comment by brisingraerowing** [comment]
That would probably work.

**Comment by Brian-Wuest** [comment]
Closing this issue. If there are more suggestions please talk about them with the rest of the community on our discord server!
