### ISSUE TITLE
Moderate House issues

### ISSUE THREAD

**Issue by BedrockLegends** [Brian-Wuest/MC-Prefab#149]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.16.3
    1. Forge Version: 34.1.1
    1. Mod Version:prefab-1.6.2.0
1. What type of issue is this? Choose one of the following:
    1. **Enhancement** (Add/Change something)
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details:
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

It seems that no all Moderate Houses have crafting Tables genning inside of them, only what feels like half do. Is there anyway to add it to the config or something to have all Moderate house gen Crafting tables

**Comment by Brian-Wuest** [comment]
I looked through all of the moderate houses and the only one I could find which didn't have a crafting table was the new mountain house.

All of the others have crafting tables but we can be a bit sneaky with how we put them. 

For example: The spruce house has the crafting tables in the floor. This reduces the space used and provides a cleaner look.
In the basement of the Acacia house the crafting tables are also in the floor in front of the furnaces.

**Comment by BedrockLegends** [comment]
ah okay, but yeah the Mountain house for sure was one that could use one, if that be in the floor or something

**Comment by Brian-Wuest** [comment]
This has been fixed with Release 1.6.2.1 which will be available on curseforge once it is approved.

Thank you for finding this!
