### ISSUE TITLE
Upgrade to Chicken Coop

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#15]
It was requested that an upgrade be made for the Chicken Coop so it could be designed to automatically collect eggs instead of causing the player to have to manually collect them.

The building should be able to allow the player to easily add chickens to the coop and a way for the player to collect the eggs via a chest.

**Comment by IamAlathe** [comment]
Yay!  I'm sure it could be done fairly easily with hoppers and a few tweaks.  Thanks!

**Comment by Brian-Wuest** [comment]
This has been released with version 1.1.1.6.

**Comment by IamAlathe** [comment]
I was distracted in the wastelands of Fallout 4 when this happened.  Thank you, Rock On!
