### ISSUE TITLE
Preview Crash w/ CTM Mod

### ISSUE THREAD

**Issue by WenXin20** [Brian-Wuest/MC-Prefab#150]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft v1.15.2
    1. Forge v31.2.36
    1. Prefab v1.5.0.9
    1. [CTM v1.1.1.13](https://www.curseforge.com/minecraft/mc-mods/ctm)
1. What type of issue is this? Choose one of the following:
    - [x] **Bug** 
    - [ ] **Enhancement**
1. Details:
   - After pressing the preview button in the Monster Structure, my game crashed. It looks like it crashed because of the CTM mod and the custom resource pack I had made with that mod.
[Crash Report](https://gist.github.com/WenXin20/b47a2c5b99ae87e49403048973658c4f)
Pack used: [MC Connected CTM v1.0.zip](https://github.com/Brian-Wuest/MC-Prefab/files/5321052/MC.Connected.CTM.v1.0.zip)

**Comment by Brian-Wuest** [comment]
Please create an issue with the CTM team to address an issue that they have. There isn't anything I can do in my code outside of not letting you use the preview function when the CTM mod exists.

**Comment by tterrag1098** [comment]
No, you're passing a nullable IModelData result to a non-null parameter. This is breaking the contract. Check for null and use EmptyModelData.
