### ISSUE TITLE
Prefab: Boundaries and Stair Rotation/Two Questions in One

### ISSUE THREAD

**Issue by AlyssaNodecraft** [Brian-Wuest/MC-Prefab#151]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14.4
    1. Forge Version: 28.2.23
    1. Mod Version: 1.4.0.18
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
    1. **Enhancement** (Add/Change something)
One bug.
One enhancement.
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details:
Enhancement: When loading structures on a superflat world, it will not allow you to do so if the structure goes past bedrock. I get it, you don't want people to put gaping holes into their worlds, but instead, maybe a warning and allow the person to still create the structure. Not sure of that on the coding side of things, but if I was a kiddo about to put a hole in my world, I might heed that warning lol.
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.
No PasteNin necessary, as there is no crash log. I just notice when placing any amount of stairs, any width, in any direction that they were all sideways and not rotated correctly to actually walk up them. This is when using the create structure feature>stairs.

**Comment by AlyssaNodecraft** [comment]
Woops. My biscuits. This isn't even your mod, but I have used so many of yours recently. Totally my bad!

**Comment by AlyssaNodecraft** [comment]
This is also why I shouldn't have so many things open at one time. re-opening due to my own disorganization. -_-

**Comment by Brian-Wuest** [comment]
For the stairs item can you create a that as a separate issue so I can handle that separately?

If that is still a defect in the 1.15 version of the mod I will fix it there. 1.14 no longer has support.

As for the bedrock issue. There was a bug reported a while ago that these structures allowed a player to break through a mods world-generated buildings. These buildings were part of a complex and pretty awesome dungeon crawler that had multiple invisible and unbreakable blocks around certain areas to force players down a particular path and not cheese their way through it.

With how the mod was originally designed it could break _anything_ thus breaking the immersion of that mod as well as like you said putting holes in the world.

I recently updated the messaging the message the player gets to tell them where the unbreakable block is. Previously it wouldn't tell you and players were very confused.
