### ISSUE TITLE
[1.16.4] Greenhouse Missing 2 slabs

### ISSUE THREAD

**Issue by TwilightPSN** [Brian-Wuest/MC-Prefab#156]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.16.4
    1. Forge Version: 35.1.0
    1. Mod Version:1.6.4.0
1. What type of issue is this? Choose one of the following:
   Bug
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. 
When you use the Greenhouse, it is built with 2 Glass Slabs missing on the roof by the door. Not sure if this is intended or being missed.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.6.4.1 which has just been made available on CurseForge.

Thank you for finding this!
