### ISSUE TITLE
[1.12.2] End portal prefab places blocks players and ops can't get rid of.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#158]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.12.2
    1. Forge Version:
    1. Mod Version: prefab-1.3.0.26
1. What type of issue is this? Choose one of the following:
    1. **Bug**  I thought we dealt with this in the past already, but we have blocks we can't get rid of from a prefab portal, worldedit won't' do it, creative mode won't do it, holding a barrier block in your hand doesn't show it.

![image](https://user-images.githubusercontent.com/4427684/101263051-e7e46f00-36ff-11eb-8250-a47910888063.png)

**Comment by Brian-Wuest** [comment]
You can give them a restore signal like with a lever on an adjacent block.

**Comment by ProsperCraft** [comment]
I see now, thank you.
