### ISSUE TITLE
Unable to spawn a structure.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Brian-Wuest/MC-Prefab#160]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.16.4
    1. Forge Version: 1.16.4 - 35.1.32
    1. Mod Version: prefab-1.6.4.2
1. What type of issue is this? Choose one of the following:
    1. **Bug** 
    
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.
2. 
https://gfycat.com/PalatableMammothCottontail

When placing a Prefab the Prefab thing is used but no house appears. I made a gif that shows everything. At the time of this post I have not yet manually tested it alone. I am going to be doing that later also I will post my modlist no logs tell us anything.

**Comment by P3rf3ctXZer0** [comment]
Unfortunately testing revealed that it is not directly caused by prefabs. Ergo one of the mods must be mutating code.

**Comment by P3rf3ctXZer0** [comment]
Current Modlist 

Name                                      
  [___MixinCompat-0.8___].jar             
  [1.12.2] SecurityCraft v1.8.20.2.jar    
  AbyssalCraft Integration-1.12.2-1.11.2.jar
  AbyssalCraft-1.12.2-2.0.0-ALPHA-1.jar   
  AmbientSounds_v3.0.18_mc1.12.2.jar      
  antighost-1.12-forge14.21.1.2387-1.1.1.jar
  AppleCore-mc1.12.2-3.4.0.jar            
  ApriTree-2.4.0.jar                      
  Architect-MC1.12-1.2.0.6.jar            
  architecturecraft-1.12-3.98.jar         
  armoryexpansion-2.0.0-alpha.jar         
  AttributeFix-1.12.2-1.0.10.jar          
  AutoRegLib-1.3-32.jar                   
  Baubles-1.12-1.5.2.jar                  
  BetterAdvancements-1.12.2-0.1.0.77.jar  
  bettercaves-1.12.2-2.0.4.jar            
  BetterDiving-1.12.2-1.5.8.jar           
  BetterMineshaftsForge-1.12.2-2.1.1.jar  
  BetterPingDisplay-1.12.2-1.0.jar        
  biolib-1.1.2.jar                        
  Biome_Bundle_O_Plenty-1.12.2_v1.0.jar   
  Biome_Bundle-1.12.2-v6.1.jar            
  BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar
  Botania r1.10-363.jar                   
  BuildingGadgets-2.8.4.jar               
  champions-1.12.2-1.0.11.9.jar           
  ChestTransporter-1.12.2-2.8.8.jar       
  Chisel-MC1.12.2-1.0.2.45.jar            
  chiselsandbits-14.33.jar                
  CompactVoidMiners-R1.11.jar             
  conarm-1.12.2-1.2.5.9.jar               
  controllable-1.12.2-0.8.0.jar           
  Controlled Burn-1.12.2.022.jar          
  Controlling-3.0.10.jar                  
  CosmeticArmorReworked-1.12.2-v5a.jar    
  CraftingTweaks_1.12.2-8.1.9.jar         
  CraftTweaker2-1.12-4.1.20.609.jar       
  CreativeCore_v1.10.34_mc1.12.2.jar      
  CTM-MC1.12.2-1.0.2.31.jar               
  Cucumber-1.12.2-1.1.3.jar               
  DeathQuotes-1.2.0-mc1.12-forge.jar      
  Dregora-1.12.2-v1.66.2.jar              
  DynamicTrees-1.12.2-0.9.21.jar          
  DynamicTreesBOP-1.12.2-1.4.4.jar        
  DynamicTreesNatura-1.12.2-1.1.6.jar     
  DynamicTreesPamTrees-1.12.2-1.0.4.jar   
  DynamicTreesQuark-1.12.2-1.0.6.jar      
  DynamicTreesTinkersConstruct-1.12.2-1.2.6.jar
  EnderCore-1.12.2-0.5.76.jar             
  EnderIO-1.12.2-5.2.66.jar               
  EnderIO-endergy-1.12.2-5.2.66.jar       
  EndReborn [0.3.9].jar                   
  exposer-1.2.jar                         
  ExtraBitManipulation-1.12.2-3.4.1.jar   
  fairylights-2.2.0-1.12.2.jar            
  fancymenu_1.6.0.1_MC_1.12-1.12.2.jar    
  FantasticLib-1.12.2.044.jar             
  FasterLadderClimbing-1.12-0.1-146.jar   
  FastFurnace-1.12.2-1.3.1.jar            
  FastLeafDecay-v14.jar                   
  FastWorkbench-1.12.2-1.7.3.jar          
  flatcoloredblocks-mc1.12-6.8.jar        
  foamfix-0.10.11-1.12.2.jar              
  Forgelin-1.8.4.jar                      
  FTBLib-5.4.7.2.jar                      
  FTBMoney-1.2.0.47.jar                   
  FTBQuests-1202.9.0.15.jar               
  FTBUtilities-5.4.1.131.jar              
  gottagofast-1.1.jar                     
  Hwyla-1.8.26-B41_1.12.2.jar             
  InventoryHud_1.12.2.forge-3.1.9.jar     
  ironchest-1.12.2-7.0.72.847.jar         
  ItemFilters-1.0.4.2.jar                 
  ItemPhysic_Full_1.4.34_mc1.12.2.jar     
  jei_1.12.2-4.16.1.302.jar               
  jeiintegration_1.12.2-1.6.0.jar         
  journeymap-1.12.2-5.7.1.jar             
  just-enough-harvestcraft-1.12.2-1.7.2.jar
  JustEnoughIDs-1.0.3-55.jar              
  JustEnoughResources-1.12.2-0.9.2.60.jar 
  konkrete_1.1.1_MC_1.12-1.12.2.jar       
  lanserverproperties-1.0.jar             
  LargeFluidTank-12.5.2.jar               
  LibraryEx-1.12.2-1.2.1.jar              
  limelib-1.12.2-1.7.12.jar               
  LittleTiles_v1.5.0-pre199_73_mc1.12.2.jar
  lt3dimporter-0.3.jar                    
  LunatriusCore-1.12.2-1.2.0.42-universal.jar
  Mantle-1.12-1.3.3.55.jar                
  maxpotidext-1.0.3.jar                   
  Mekanism-1.12.2-9.8.3.390.jar           
  MekanismGenerators-1.12.2-9.8.3.390.jar 
  memorycleaner-1.2.jar                   
  Metallurgy-4-Reforged-1.2.2.jar         
  MixinBootstrap-1.0.5.jar                
  MoreBuckets-1.12.2-1.0.4.jar            
  morerefinedstorage-1.1.9.jar            
  MouseTweaks-2.10-mc1.12.2.jar           
  MysticalAdaptations-1.12.2-1.8.4.jar    
  MysticalAgradditions-1.12.2-1.3.2.jar   
  MysticalAgriculture-1.12.2-1.7.5.jar    
  MysticalCreations-1.12.2-1.6.jar        
  natura-1.12.2-4.3.2.69.jar              
  NetherEx-1.12.2-2.2.2.jar               
  nevoka-core-1.0.2.jar                   
  NomadicTents-1.12.2-9.5.2.jar           
  OnlinePicFrame_v1.5.0-pre1_mc1.12.2.jar 
  OpenTerrainGenerator-1.12.2-v9.3.jar    
  OreExcavation-1.4.150.jar               
  OTG-Skylands-1.12.2-v5.jar              
  Pam's HarvestCraft 1.12.2zg.jar         
  Patchouli-1.0-22.jar                    
  phosphor-forge-mc1.12.2-0.2.7-universal.jar
  PickleTweaks-1.12.2-2.1.3.jar           
  Pixelmon-1.12.2-8.1.2-universal.jar     
  PixelmonInformation-1.12.2-8.0.0-0.3.7.jar
  Placebo-1.12.2-1.6.0.jar                
  Plants-1.12.2-2.10.7.jar                
  prefab-1.3.0.26.jar                     
  projectstorage-1.12.2-1.3.jar           
  Quark-r1.6-179.jar                      
  randompatches-1.12.2-1.22.1.10.jar      
  randomtweaks-1.12.2-2.8.2.2.jar         
  rbmf_1.12-1.0.jar                       
  RebornCore-1.12.2-3.19.4.529-universal.jar
  RebornStorage-1.12.2-3.3.4.1.jar        
  refinedstorage-1.6.16.jar               
  refinedstorageaddons-0.4.5.jar          
  refinedstoragerequestify-1.12.2-1.0.2-3.jar
  rsgauges-1.12.2-1.2.5.jar               
  scalingfeast-1.6.1.jar                  
  ScalingHealth-1.12.2-1.3.42+147.jar     
  Schematics-1.12.2.12.jar                
  SilentLib-1.12.2-3.0.14+168.jar         
  SmoothFont-mc1.12.2-2.1.2.jar           
  solcarrot-1.12.2-1.8.4.jar              
  SpiceOfLife-mc1.12-1.3.12.jar           
  Stackie-1.12.2-1.6.0.48-universal.jar   
  stellarfluidconduit-1.12.2-1.0.3.jar    
  stg-1.12.2-1.2.3.jar                    
  StorageTech R6.0.jar                    
  stygian-1.0.4.jar                       
  supersoundmuffler-revived_1.12.2_1.0.2.10.jar
  TConstruct-1.12.2-2.13.0.183.jar        
  tellme-1.12.2-0.7.0-dev.20200919.184303.jar
  TheBetweenlands-3.7.2-universal.jar     
  thutcore-1.12.2-5.21.0.jar              
  thuttech-1.12.2-6.1.6.jar               
  tinker_io-1.12.2-rw2.8.3.jar            
  tinkers_reforged-1.5.0.jar              
  TinkersComplement-1.12.2-0.4.3.jar      
  tinkersdefense-1.4.2.38.jar             
  tinkersjei-1.2.jar                      
  TinkerToolLeveling-1.12.2-1.1.0.jar     
  Toast Control-1.12.2-1.8.1.jar          
  tombstone-4.0.1-1.12.2.jar              
  tweakersconstruct-1.12.2-1.5.5.jar      
  UnlimitedChiselWorks-0.3.4.jar          
  WailaHarvestability-mc1.12-1.1.12.jar   
  walljump-1.12.2-1.3.2.jar               
  Wawla-1.12.2-2.6.275.jar                
  
  If anything stands out let me know -- I will begin the slog now.

**Comment by P3rf3ctXZer0** [comment]
Modlist 

Name                                     	Date modified
  [1.16.4]LagMeter-1.3.4.jar             	             
  abnormals_core-1.16.4-3.0.6.jar        	             
  AI-Improvements-1.16.2-0.3.0.jar       	             
  AmbientSounds_v3.1.4_mc1.16.4.jar      	             
  Apotheosis-1.16.3-4.4.1.jar            	             
  AppleSkin-mc1.16.2-forge-1.0.14.jar    	             
  Aquaculture-1.16.4-2.1.11.jar          	             
  AttributeFix-1.16.4-9.0.2.jar          	             
  AudioCassettes-1.16.4-1.1.jar          	             
  AutoRegLib-1.6-47.jar                  	             
  autumnity-1.16.4-2.0.1.jar             	             
  BetterAdvancements-1.16.4-0.1.0.103.jar	             
  BetterPingDisplay-1.16.4-1.0.jar       	             
  BiomesOPlenty-1.16.4-13.0.0.427-universal.jar	             
  Bookshelf-1.16.4-9.3.18.jar            	             
  Botania-1.16.4-410.jar                 	             
  BotaniaAdditionsMC1.16.4-1.0.4.jar     	             
  botanicalmachinery-1.16.4-0.3.1.jar    	             
  buildinggadgets-1.16.4-3.7.3.jar       	             
  Cazfps_lamps_1.16.4.jar                	             
  champions-forge-1.16.4-2.0.0.2.jar     	             
  chiselsandbits-0.2.8-RELEASE.jar       	             
  chocolate-1.2.0-1.16.4.jar             	             
  comforts-forge-1.16.4-4.0.1.0.jar      	             
  Controller Support-1.16.4-4.0.3.jar    	             
  Controlling-7.0.0.11.jar               	             
  CosmeticArmorReworked-1.16.4-v1.jar    	             
  CraftingTweaks_1.16.3-12.2.0.jar       	             
  CraftTweaker-1.16.4-7.0.0.63.jar       	             
  CreativeCore_v2.0.10_mc1.16.4.jar      	             
  Cucumber-1.16.4-4.1.5.jar              	             
  curios-forge-1.16.4-4.0.3.3.jar        	             
  dankstorage-3.13.jar                   	             
  EnchantmentDescriptions-1.16.4-6.0.2.jar	             
  extlights-3.3.jar                      	             
  extradisks-1.16.4-1.3.4.jar            	             
  ExtraStorage-1.16.4-1.2.2.jar          	             
  extremeSoundMuffler-3.4_Forge-1.16.4.jar	             
  fairylights-4.0.4-1.16.4.jar           	             
  fancymenu_1.6.0_MC_1.16.2-1.16.4.jar   	             
  farlanders-1.16.4-1.3.6.jar            	             
  FastFurnace-1.16.3-4.3.0.jar           	             
  FastLeafDecay-v25.jar                  	             
  FastWorkbench-1.16.3-4.4.1.jar         	             
  FCB-1.0.jar                            	             
  flickerfix-1.0.0.jar                   	             
  ftb-chunks-1604.2.2.56.jar             	             
  ftbessentials-1603.1.0.11.jar          	             
  ftb-gui-library-1604.1.1.26.jar        	             
  ftb-quests-1604.1.1.21.jar             	             
  ftb-ranks-1604.1.1.9.jar               	             
  ftb-teams-1604.1.0.13.jar              	             
  ftb-ultimine-1603.1.1.13.jar           	             
  furniture-7.0.0-pre19-1.16.3.jar       	             
  Gobber2-1.16.4-2.3.42.jar              	             
  gottaclimbfast-mc1.16-1.1-forge.jar    	             
  ironchest-1.16.4-11.2.10.jar           	             
  item-filters-1604.2.2.19.jar           	             
  ItemPhysic_v1.4.14_mc1.16.4.jar        	             
  jei-1.16.4-7.6.1.65.jar                	             
  jeiintegration_1.16.4-6.1.1.11.jar     	             
  JEITweaker-1.16.4-1.0.1.5.jar          	             
  JustEnoughResources-1.16.4-0.12.0.103.jar	             
  konkrete_1.1.1-2_MC_1.16.2-1.16.4.jar  	             
  LibX-1.16.3-1.0.10.jar                 	             
  managear-1.16.3-2.2.3.jar              	             
  mcjtylib-1.16-5.0.15.jar               	             
  mcw-bridges-1.0.4-mc1.16.4.jar         	             
  mcw-doors-1.0.1fix-mc1.16.4.jar        	             
  mcw-furniture-2.0.0-mc1.16.4.jar       	             
  mcws-roofs-2.0.0-mc1.16.4.jar          	             
  mcw-windows-1.0.2-mc1.16.4.jar         	             
  Mekanism-1.16.4-10.0.18.445.jar        	             
  MekanismGenerators-1.16.4-10.0.18.445.jar	             
  MekanismTools-1.16.4-10.0.18.445.jar   	             
  ModernUI-1.16.4-2.3.2.71-universal.jar 	             
  MouseTweaks-2.13-mc1.16.2.jar          	             
  MysticalAgradditions-1.16.4-4.1.3.jar  	             
  MysticalAgriculture-1.16.4-4.1.4.jar   	             
  NetherPortalFix_1.16.3-7.2.1.jar       	             
  pamhc2crops-1.16.3-1.0.1.jar           	             
  pamhc2foodcore-1.16.3-1.0.0.jar        	             
  pamhc2foodextended-1.16.3-1.0.0.jar    	             
  pamhc2trees-1.16.3-1.0.0.jar           	             
  Patchouli-1.16.4-48.jar                	             
  performant-1.16.2-4-3.28m.jar          	             
  PickleTweaks-1.16.4-5.1.4.jar          	             
  Placebo-1.16.3-4.3.3.jar               	             
  pokecube-aio-1.16.4-3.6.1.jar          	             
  prefab-1.6.4.2.jar                     	             
  QuarkOddities-1.16.3.jar               	             
  Quark-r2.4-289.jar                     	             
  randompatches-2.1.5-forge.jar          	             
  recipebuffers-2.0.jar                  	             
  refinedpipes-0.5.jar                   	             
  refinedstorage-1.9.11.jar              	             
  refinedstorageaddons-0.7.2.jar         	             
  rftoolsbase-1.16-2.0.9.jar             	             
  rftoolsbuilder-1.16-3.0.13.jar         	             
  rftoolspower-1.16-3.0.8.jar            	             
  rsrequestify-1.16.3-2.0.1.jar          	             
  ScalingHealth-1.16.4-4.0.2+2.jar       	             
  shutupexperimentalsettings-1.0.1.jar   	             
  SilentGear-1.16.3-2.4.11+200.jar       	             
  SilentGems-1.16.3-3.7.7+110.jar        	             
  SilentLib-1.16.3-4.9.0+63.jar          	             
  SimpleCoreLib-1.16.4-2.0.4.3.jar       	             
  SimpleOres2-1.16.4-2.4.3.8.jar         	             
  smoothboot-forge-1.16.4-1.2.0.jar      	             
  SpartanShields-1.16.4-2.1.0-beta-1.jar 	             
  SpartanWeaponry-1.16.4-2.1.0-beta-2.jar	             
  storagetech-1.16.4-R1.3.jar            	             
  structure-gel-api-1.16.4-1.7.2.jar     	             
  the_bumblezone-1.16.4-2.2.8.jar        	             
  theoneprobe-1.16-3.0.7.jar             	             
  thutcore-1.16.4-8.1.1.jar              	             
  thuttech-1.16.4-9.1.0.jar              	             
  Toast-Control-1.16.3-4.3.0.jar         	             
  tombstone-1.16-6.2.3.jar               	             
  tumbleweed-1.16-0.4.9.jar              	             
  upsizer-mc1.16.4-6.1.jar               	             

If anything stands out please let me know. I will begin the slog of testing.

**Comment by P3rf3ctXZer0** [comment]
Ironically the mutation is caused by modern GUI.

**Comment by Brian-Wuest** [comment]
Well this is a roller coaster! 

Can you check you log file and include that? I can check this out in the morning.

**Comment by P3rf3ctXZer0** [comment]
I did check the log and debug NOTHING tells us anything. I just removed modern UI for the time being. It's just when the two mods are together the code mutates. If you create a debug version of prefabs I can test it for you if you seek more info.

**Comment by Brian-Wuest** [comment]
Thank you for the offer but having it narrowed down to that one mod is extremely helpful. I will see if there's anything I can do in my mod to avoid it.

**Comment by Brian-Wuest** [comment]
So I set up a temp modpack with just a few mods in it and I cannot duplicate this behavior.

When I just have JEI, Modern UI, and Prefab, structures are generated as expected.

![image](https://user-images.githubusercontent.com/13502068/103889194-a272e300-50ab-11eb-984c-7207ade2c2f1.png)

**Comment by P3rf3ctXZer0** [comment]
your forge version is incorrect I am using 1.16.4 35-1-32

**Comment by Brian-Wuest** [comment]
I wasn't able to duplicate this even the latest version of forge (35.1.36).

See Imgur

https://imgur.com/a/0t9sTBS

**Comment by P3rf3ctXZer0** [comment]
Curious.

**Comment by P3rf3ctXZer0** [comment]
All I know is removing that mod made the pack work ... Lets close this for now I will reopen it if I somehow run into things again the future.

**Comment by Brian-Wuest** [comment]
Yeah, let me know as I am curious too!

Could be a number of mod interactions....

**Comment by P3rf3ctXZer0** [comment]
I can narrow it down. 
[Prefab-1.0.zip](https://github.com/Brian-Wuest/MC-Prefab/files/5790575/Prefab-1.0.zip)

It contains 9 mods use curse or gdlauncher for testing.

Import the zip. Launch game. Make sure you also have these java args for full test environment expirence. 

-> -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m <-

Ram size 6GB

**Comment by Brian-Wuest** [comment]
Still unable to duplicate.

I am on windows 10 and using the built-in Intel Graphics if that's a factor.

I did use your JAVA Args, I am on Java 271 if that also matters.

Here's the Imgur.

https://imgur.com/a/I6Essgn

**Comment by P3rf3ctXZer0** [comment]
hm ... damn I have no idea then. This is the most obscure issue I have ever encountered. I will close this again unless we get some major info or figure out what caused it. ... The only thing I can guess is some kind of anomaly.
