### ISSUE TITLE
Build right after Preview?

### ISSUE THREAD

**Issue by khdhhde21** [Brian-Wuest/MC-Prefab#161]
I'm using Prefab in Creative. After previewing a house, is there a way to build it right away, or is it always necessary to right click and press on the "Build" button again? In that case it's possible that the house will be built at a location different from where it was previewed originally.

**Comment by Brian-Wuest** [comment]
It is certainly possible to build it in a different location. I have been thinking of adding some more animation or graphics to show what you clicked on.

It would probably be harder to implement a preview and build.

**Comment by khdhhde21** [comment]
Would it be possible to add a hotkey that would build right from the preview?

**Comment by Brian-Wuest** [comment]
We could probably do a HotKey, not sure what the default could be so it didn't interfere with other mods too much.

Any suggestions?

**Comment by Brian-Wuest** [comment]
Oh! I also was able to get an indicator box of where the player clicked when showing the preview!

Here's what I've got so far!

Thoughts?

![2021-01-13_21 17 40](https://user-images.githubusercontent.com/13502068/104540682-8f996a80-55e5-11eb-9286-86775fe648f3.png)

**Comment by khdhhde21** [comment]
> 
> 
> We could probably do a HotKey, not sure what the default could be so it didn't interfere with other mods too much.
> 
> Any suggestions?

I guess it could interfere no matter what we choose, but the user could always change it in the options. Or, maybe some combination of shift and a mouse button if it's easier? Sorry, no experience developing mods yet :)


The indicator box seems like a very useful addition.

**Comment by Brian-Wuest** [comment]
Here's how it works with a keybinding (Currently: Alt + B)

![Structure_Gen3](https://user-images.githubusercontent.com/13502068/104816234-57f61280-57df-11eb-960c-fa64550f8d9f.gif)

**Comment by Brian-Wuest** [comment]
I am going to test out all of the other structures before I release this but I am happy with the results.

**Comment by Brian-Wuest** [comment]
This has been released with version 1.6.4.3 and is now available on curseforge!

Thank you for bringing this idea up!

**Comment by khdhhde21** [comment]
Just checked it. Alt+B works great. Thank you for the terrific mod!

PS. Maybe add some relevant help text to "Right-click on any block in the world to remove the preview"?

**Comment by Brian-Wuest** [comment]
yeah; i could see what other text I can add to that.
