### ISSUE TITLE
1.16.5 - Prefab Datapack Error.

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Brian-Wuest/MC-Prefab#162]
1. What version of Minecraft, Forge and Mod are you running?
- Minecraft Version: 1.16.5
- Forge Version: 36.0.1
- Mod Version: 1.6.5.0

2. What type of issue is this? Choose one of the following:
- **Bug**

Screenshot of the error message: https://cdn.discordapp.com/attachments/658744395222351882/803400363004264488/Error.jpg
https://pastebin.com/J1uLuK0B Error log

Steps to reproduce:
1. Load into single-player world.
2. Place down any prefab building 
3. save and quit to menu
4. load up the world
5. error.
6. profit?

**Comment by Brian-Wuest** [comment]
Works fine with the following
1. Forge: 36.0.4
2. Mod Version: 1.6.5.0
3. SuperFlat world
4. Classic flat with 50 layers of dirt
5. Generate structures off
6. Difficulty: Peaceful

Also; looking over your log doesn't show anything that would indicate Prefab. All of the call stacks either point in Forge or Minecraft.

Additionally it looks like Forge fixed some issues with Biomes in the latest builds.
Try updating to the latest Forge and see if that works.

**Comment by Brian-Wuest** [comment]
Closing as it has been almost two weeks without response from OP.
