### ISSUE TITLE
Wither rose in nether gate can cause balancing issues

### ISSUE THREAD

**Issue by ThugPug43** [Brian-Wuest/MC-Prefab#165]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.16,5
    1. Forge Version: 36.1.0
    1. Mod Version: 1.6.5.0
1. What type of issue is this? Choose one of the following:
  1. **Enhancement**
    
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details: In the newest variant of the nether gate (the tree one not the skull one), a wither rose is included with the build. While structures in the past have provided resources that are difficult to obtain (like the fish pond giving slime) the inclusion of the wither rose allows people to entirely skip vanilla progression for the item. This as a result can throw off the balance of other mods that utilize the vanilla gating of the wither rose to ensure certain items won't be obtainable until the player reaches a certain point.
    
    EDIT: I forgot to provide an example. Resourceful Bees uses the wither rose as the flower a wither bee pollinates. With the wither rose being obtainable through the structure rather than a wither killing a mob, it is possible to access the full potential of the wither bees without killing a single wither skeleton.

**Comment by Brian-Wuest** [comment]
I haven't honestly played the game in a _long_ time and am unaware of the gating in the game. I also noticed crimson fungus on the outside. Is that also something that should be removed?

**Comment by ThugPug43** [comment]
Crimson fungus is fine it's an easily obtainable nether item.

**Comment by Brian-Wuest** [comment]
Fixed with: 3ecae95

Will be releasing this shortly. Have a few other things to look at first.

**Comment by Brian-Wuest** [comment]
This has been released on CurseForge with version 1.6.5.1 and will be available when they approve the release.

Thank you for finding this issue!
