### ISSUE TITLE
Infinite Houses [1.6.5.0] version

### ISSUE THREAD

**Issue by Hir0shiyt** [Brian-Wuest/MC-Prefab#166]
1. What version of Minecraft, Forge and Mod are you running?
    I. Minecraft Version: 1.16.5
    II. Forge Version: 36.1.0
    III. Mod Version: 1.6.5.0
1. What type of issue is this? 
   I have "b" to build the house instantly, When i press preview  and then i press "b" i have infinite houses idk if this is normal [Part of the mod] or is a bug i'll try to make a video about this

because i have a not good pc so..

I'll wait for your response
Thanks for the attention

**Comment by Brian-Wuest** [comment]
I am unable to duplicate the issue you are describing. The hot-key works just fine during preview. It is generating the building and removing the item from the players inventory.

**Comment by Hir0shiyt** [comment]
https://www.youtube.com/watch?v=zJD_iyKRiKc

Here is the video

The Evidence

**Comment by Brian-Wuest** [comment]
Wow, thank you for that! I hadn't thought to put the building in my offhand.

I will take a look at this after work today.

Thank you!

**Comment by Hir0shiyt** [comment]
Sure if u need more help just say to me on discord

https://discord.gg/58cfDTkV

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.6.5.2 which has been uploaded to curse forge. 

This will be available once it goes through their approval process.

Thank you for finding this issue!

Closing
