### ISSUE TITLE
Not sure why this is happening

### ISSUE THREAD

**Issue by ModernGamingWorld** [Brian-Wuest/MC-Prefab#167]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.16.5
    1. Forge Version: 36.1.16
    1. Mod Version: 1.16.5.3

This is a fairly weird bug to say the lest, I have no idea why its happening. I just know someone keeps complaining that its a bug when idk even know what's causing it
![unknown](https://user-images.githubusercontent.com/75923060/117886963-970c1000-b275-11eb-9e02-4448205b024f.png)

**Comment by Brian-Wuest** [comment]
Probably that the server side configuration has that recipe disabled. If they are the server admin they need to check that value. I have found that forge made their configuration file locations pretty complicated since they released 1.13 and later.

There is sometimes a defaultconfigs folder that they need to setup since it us generated for each save.

**Comment by ModernGamingWorld** [comment]
its on my server and it only happens with that server side mod in that I link @Brian-Wuest

**Comment by Brian-Wuest** [comment]
Just set up a brand new server with default configurations for both mods specified.

Latest version of forge (36.1.16)
Latest version of Adaptive Performance Tweaks (0.4.5)
Latest version of Prefab (1.6.5.3)

Launching server through Forge JAR.
Launching client through official Minecraft Client (Not CurseForge Client or FTB Client)

I am unable to duplicate this issue, see screenshot below.

Screen shot
![image](https://user-images.githubusercontent.com/13502068/117963236-b6428600-b2e5-11eb-8517-522cb79f5a60.png)

**Comment by MarkusBordihn** [comment]
Unfortunately I was not able to reproduce the issue on one of my test servers (with 210+ Mods) with different kind of workbenches.

![2021-05-12_13 59 19](https://user-images.githubusercontent.com/12183293/117971636-7356d180-b32a-11eb-9604-b9e95a9a327f.png)
![2021-05-12_13 58 13](https://user-images.githubusercontent.com/12183293/117971647-75b92b80-b32a-11eb-8d1f-e28aa7c54e81.png)

@ModernGamingWorld 
Would be great to get a reliable way to reproduce the issue.
