### ISSUE TITLE
[Enhancement] Workshop house (Moderate house) includes too much for the cost compared to other options from the same Moderate house tier

### ISSUE THREAD

**Issue by Electrofried** [Brian-Wuest/MC-Prefab#168]
Minecraft Version: 1.16.5
Forge Version:  36.1.16
Mod Version:  1.6.5.3

The workshop house is extremely over value for the cost of making it and what it includes compared to the other Moderate houses, with multiple hoppers and automation systems, redstone, pistons, and to top it all off two enchanting tables. As far as I can tell there is no way to simply disable this one house option in the config.  

While I love the house design and what it offers I feel it really would be better as a separate 'Workshop' option that perhaps requires something similar to the Warehouse Upgrade to craft.

**Comment by Brian-Wuest** [comment]
Recipe wise; would you see this with a singular moderate house item with a warehouse upgrade? Two moderate house items with warehouse upgrade?

Otherwise I could add a configuration option to disable this option for servers.

**Comment by Electrofried** [comment]
I love the building and would prefer the option to still have it available at a suitable cost, Personally I feel a single moderate house with a warehouse upgrade covers the costs associated with the items in the Workshop as you have a couple of blaze rods you will be 'losing' along with an anvil if you decide to separate it out to a new "Workshop" prefab.

**Comment by Brian-Wuest** [comment]
That seems reasonable to me.

I will work with Kaojin to get a new texture for it.

**Comment by Brian-Wuest** [comment]
@Electrofried - As a head's up I am doing some last touches on this release (1.6.5.4) before I push out the release. Will be hoping for later this week if other life stuff doesn't get in the way 😄

**Comment by Brian-Wuest** [comment]
Sorry it took so long but there was a lot I wanted to do for this release.

The update for this issue has been pushed with version 1.6.5.4 on Curseforge and will be available when they approve the file.

Thank you!
