### ISSUE TITLE
Overlapping text

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#176]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.16.5
    1. Forge Version: 36.1.0
    1. Mod Version: 1.6.5.5
2. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
3. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

Translated text is overlapping or going out of bounds in some items:

<img width="1440" alt="2" src="https://user-images.githubusercontent.com/27054231/120539930-a2b3a800-c3d7-11eb-9516-6e8142dedf71.png">

<img width="1440" alt="1" src="https://user-images.githubusercontent.com/27054231/120539950-a810f280-c3d7-11eb-8172-744df0e3ea8b.png">

Language on the screenshots: Russian

**Comment by Brian-Wuest** [comment]
Thanks, I will try to get that updated this weekend (it's my son's birthday weekend).

Also you have been on a role with pull requests and bug reports so I want to give you some time to find or fix more things.

I don't like pushing out a ton of releases.

**Comment by Dqu1J** [comment]
^ oops, sorry!

**Comment by Brian-Wuest** [comment]
Darn thing got closed; it's not done yet :)

**Comment by Dqu1J** [comment]
<img width="985" alt="1" src="https://user-images.githubusercontent.com/27054231/121098790-21e51980-c7e6-11eb-9074-1a8db9f831e7.png">

Issue still remains

**Comment by Brian-Wuest** [comment]
So it looks like you updated the translations to be much longer than what is in the repository right now.

Using the translations we currently have everything looks fine.


![image](https://user-images.githubusercontent.com/13502068/121171756-83c07600-c81c-11eb-847d-42cf4a10a440.png)

**Comment by Dqu1J** [comment]
Thats correct. I will test other languages later today.

**Comment by Dqu1J** [comment]
Issue seems to be resolved. Except tabs in the Starting House:
<img width="436" alt="" src="https://user-images.githubusercontent.com/27054231/121406277-7b1b8d00-c94d-11eb-85ba-21ef8e021646.png">
Appears in about half languages.

**Comment by Brian-Wuest** [comment]
Was able to clean up the tabs so they are readable.

I also made them wider so more text can be shown which would be able to provide more context of what the tab contains.

The example below is in Italian.

![image](https://user-images.githubusercontent.com/13502068/121455712-90eb7b00-c96a-11eb-9a86-9a0fa0b56657.png)

**Comment by Brian-Wuest** [comment]
The above commit fixes the tabs; I plan on pushing out a release this weekend for the various sizing updates as well as some of the requested enhancements for structure options.

Thank you for all of the efforts you have put in to make this mod more accessible to our non-english audience!

**Comment by Brian-Wuest** [comment]
These updates have been pushed to curseforge with version 1.6.5.6.
