### ISSUE TITLE
Enhancement Add Schematics to Create proper Structures

### ISSUE THREAD

**Issue by Switch-Back18** [Brian-Wuest/MC-Prefab#179]
1. What type of issue is this? Choose one of the following:
    1. **Enhancement**
    2. Details: It's possible to add the posibility to use Schematics or other things to create own structures or the possibility to change the actual structures (remove the furnace of all, chest,...) not just for the starting house.
    
    Thanks and have a good day !

**Comment by Dqu1J** [comment]
As said on mod's page on CurseForge: 
> There are no plans to create a feature for custom blueprints or loading custom structures outside of the ones provided by this mod. This functionality already exists with [Structurize](https://www.curseforge.com/minecraft/mc-mods/structurize) and we highly recommend it.

**Comment by Brian-Wuest** [comment]
As stated, we will not be adding the custom structures option to this mod.

As far as removing blocks from existing structures outside of the starting/moderate houses. These building can be pretty expensive so we don't want to remove these blocks as they are part of the cost of the blue print in terms of materials.
