### ISSUE TITLE
Neutered Monster Masher

### ISSUE THREAD

**Issue by kaojinn** [Brian-Wuest/MC-Prefab#18]
At the request of admins for multiplayer games, a Monster Masher building without the inclusion of spawners has been requested.  The idea is to still allow the building to be created for players to make their own spawners from mods like EnderIO and Soul Shards, but not get free ones along with it.

This will be made as a toggle option in the config file for admins to set, and will trigger an optional script to be run that will remove the spawners after the building is placed, thereby not impacting the existing design.

**Comment by Brian-Wuest** [comment]
This has been implemented in version 1.1.1.7 for Minecraft 1.10.2.
