### ISSUE TITLE
**Bug** prefabs turning into advanced chicken coop

### ISSUE THREAD

**Issue by benreckless223** [Brian-Wuest/MC-Prefab#182]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.12.2
    1. Forge Version: 14.23.5.2855
    1. Mod Version: 1.12.2
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
  
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

I go to spawn in some prefabs in creative to check em out and they turn into advanced chicken coops. For example. The barn, wathc tower, and almost all others

**Comment by Brian-Wuest** [comment]
I'm sorry but Minecraft version 1.12.2 is no longer supported.

Please update to a modern version of Minecraft.
