### ISSUE TITLE
Building glass selection doesn't allow plain glass panes

### ISSUE THREAD

**Issue by adueppen** [Brian-Wuest/MC-Prefab#183]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.16.5
    1. Forge Version: 36.1.0
    1. Mod Version: 1.6.5.5
1. What type of issue is this?
    1. **Bug/Enhancement** (I'm not sure how to best categorize this)
1. Details:
    - Several prefabs offer the ability to change the color of glass to use in the structure's windows, but plain glass isn't an option. All stained glass colors end up applying a tint so it would be nice to have plain glass available.

**Comment by Brian-Wuest** [comment]
I am surprised no one brought this up before!

This is going to take a bit to implement as Minecraft has very clear separations of Stained Glass and regular Glass.
