### ISSUE TITLE
GUI improvements

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#187]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.16.5
    1. Forge Version: 36.1.0
    1. Mod Version: 1.6.5.6
1. What type of issue is this? Choose one of the following:
    1. **Enhancement** (Add/Change something)
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details:

`prefab.gui.structure.block.clicked` is not needed because of the yellow outline of the block clicked. 

I would suggest changing it to appear when clicking on the `Preview` button, and changing it's text to something like: `The yellow outline is the block you clicked.`

**Comment by Brian-Wuest** [comment]
That's a good point.

Do you think the images are necessary anymore?

The mod would be _much_ smaller without those images.

**Comment by Brian-Wuest** [comment]
Note: I added a poll to our discord server; please join us!

It's in the "prefab ideas" channel.

https://discord.gg/BAqZGjcp

**Comment by Dqu1J** [comment]
I think that we should keep the images, or replace them with something similar. Images help see the whole structure, and preview how it would look like in your terrain.

**Comment by Brian-Wuest** [comment]
Here's what this will look like now for the Grassy Plain item GUI

![image](https://user-images.githubusercontent.com/13502068/122650891-f540d400-d0fa-11eb-8470-209e74f1fe07.png)

Here's what it looks like when showing the preview.

![2021-06-19_12 42 45](https://user-images.githubusercontent.com/13502068/122651041-e27acf00-d0fb-11eb-86db-144ed74a358b.png)


Thoughts?

**Comment by Dqu1J** [comment]
Yes! But there's a lot of white space in the GUI now, I think it needs a change?

**Comment by Dqu1J** [comment]
![Untitled](https://user-images.githubusercontent.com/27054231/122654751-11656500-d13d-11eb-8c32-c0936cfe7b30.png)
I see the GUI as something like this.
