### ISSUE TITLE
Prefab1.3.1.1 reports as ${version} in minecraft

### ISSUE THREAD

**Issue by RussellHaley** [Brian-Wuest/MC-Prefab#188]
What version of Minecraft, Forge and Mod are you running?
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2838
Mod Version: 1.3.1.1
1. What type of issue is this? Choose one of the following:
    1. **Bug** After minecraft opens from the loader I clicked on the Mods button to check the loaded version. Prefab reports as ${version} instead of 1.3.1.1

Software is fun, isn't it? ;-)

**Comment by Brian-Wuest** [comment]
Software is so much fun.....

I'll fix this with the 1.3.1.2 release.

Don't know when that is going to be right now though.
