### ISSUE TITLE
Suggestion: Translation Contributors

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#189]
1. What type of issue is this? Choose one of the following:
    1. **Enhancement** (Add/Change something)
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details:

Right now the “Translation Contributors” on CurseForge looks like this:

![image](https://user-images.githubusercontent.com/27054231/122640703-a51d3e00-d109-11eb-9afd-0b9ca434d5fd.jpeg)

And it is a bit outdated.
I'm suggesting:
1. Remove the "(1.14.4+)" label in Japanese, Turkish and Traditional Chinese, as these languages were added in 1.3.1.0
2. Add a new translation contributor: Dqu1J (GitHub) - Russian, Ukrainian
3. Add a new translation contributor: BlackWolf00 (GitHub) - Italian
4. Add a new translation contributor: Google Translate - French, Spanish

**Comment by Brian-Wuest** [comment]
Thanks for keeping us honest.

It has been updated.
