### ISSUE TITLE
Error using preview on large modpacks

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#19]
An error was reported that the game crashes when using the preview function on certain modpacks.

Error is here: http://pastebin.com/L5uftnrx

**Comment by knubbis93** [comment]
I want to add that im not able to press Build on some buildings for example Monster Masher idk if you can see that too in all the mods

**Comment by Brian-Wuest** [comment]
I am noticing that this is an issue with the "FoamFix" mod. Looking into why.

**Comment by Brian-Wuest** [comment]
I was able to figure out an alternative to the issue which FoamFix was presenting. This will be released tomorrow morning. Thank you!

**Comment by knubbis93** [comment]
Thank you very much i LOVE your mod its genius :D and thank you so much for such a fast update

**Comment by Brian-Wuest** [comment]
This has been released with version 1.1.1.7 for Minecraft 1.10.2

**Comment by knubbis93** [comment]
you're the best :D
