### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#193]
1. What version of Minecraft, Fabric and Mod are you running?
    1. Minecraft Version: 1.17
    1. Fabric Loader Version: 0.11.6
    1. Fabric API version: 0.35.2
    1. Cloth Config Version: 5.0.34
    1. Mod Version: 2.0.1
1. What type of issue is this? Choose one of the following:
    1. **Enhancement** (Add/Change something)
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details:

Some of the translation strings are not used, some are not translated.
And some text overlaps.
I suggest fixing that.

Not used strings:
- prefab.gui.fishpond.structure.facing
- prefab.gui.structure.facing
- prefab.gui.treefarm.facing
- prefab.gui.structure.facing.player
- prefab.gui.structure.door.facing
- prefab.gui.structure.block.clicked

Not translated text:
- prefab.gui.moderate_house.earthen (In Fabric version only)
- Compressed Chest item tooltip (image provided below)

<img width="339" alt="1" src="https://user-images.githubusercontent.com/27054231/124757277-ed679900-df1c-11eb-8110-054a7f91be20.png">

And, overlapping text again, is present in the structure names:
<img width="491" alt="2" src="https://user-images.githubusercontent.com/27054231/124757657-594a0180-df1d-11eb-884a-395b0a885f55.png">

Language on all the screenshots is russian.

**Comment by Brian-Wuest** [comment]
Closing; will be released with 1.6.5.7
