### ISSUE TITLE
Patterns With Water

### ISSUE THREAD

**Issue by kaojinn** [Brian-Wuest/MC-Prefab#2]
Currently nothing is preventing them from being used in The Nether, which violates vanilla water mechanics in the nether.
![oops](https://cloud.githubusercontent.com/assets/20660299/17344853/3ea61cea-58c9-11e6-8b9d-a6c87e7add40.png)

**Comment by Brian-Wuest** [comment]
The Starter House, Warehouse, Tree Farm, Produce Farm and Fish Pond will check to see if the current player's dimension is the overworld. If it isn't a chat message will be shown and the item GUI will not be displayed.

**Comment by Brian-Wuest** [comment]
Fixed in version 1.1.0.8.

Closing
