### ISSUE TITLE
Infinite houses [again]

### ISSUE THREAD

**Issue by Hir0shiyt** [Brian-Wuest/MC-Prefab#201]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version:1.16.5
    1. Forge Version:36.2.0
    1. Mod Version:1.6.5.8

First of all, sorry for this lol
Second, when you click to preview and you just throw the structure, you can just duplicate it as many times as you want
Third, You should add a craft for the bunches of every single food, it doesn't have any crafts

and yeah toy should add a netherite swift sword

If i find any other glitch i'll report it as soon as possible

**Comment by Brian-Wuest** [comment]
So you have the preview up then you use the keyboard shortcut to generate the house right?

**Comment by Hir0shiyt** [comment]
No, i just click preview, then press q with the building in my hand(not the off-hand) and then i press "m" 

M is the letter that i use to build the house

**Comment by Brian-Wuest** [comment]
This will be available in the next releases for 1.16.5 and 1.17.1.
