### ISSUE TITLE
Water in non-overworld dimensions

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#204]
1. What version of Minecraft, Forge and Mod are you running?
    1. source
1. What type of issue is this? Choose one of the following:
    1. **Enhancement** (Add/Change something)
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.

This line:
`if (!World.OVERWORLD.getValue().toString().equals(world.getRegistryKey().getValue().toString()))` in `src/main/java/com/wuest/prefab/structures/base/Structure.java`
Will remove water everywhere except overworld. The water should still be present in the end, and modded dimensions that allow water in them.

To solve that, In Fabric, there is `DimensionType.isUltrawarm()` ([link](https://maven.fabricmc.net/docs/yarn-1.17.1+build.38/net/minecraft/world/dimension/DimensionType.html#isUltrawarm())), which will be true if there can’t be water. It also works with modded dimensions. I’m not sure about Forge, but there should be a value for this too.

**Comment by Brian-Wuest** [comment]
We will also be adding a configuration option to determine if the End can have water through the prefabs. By default this will be turned on. Modpack developers can turn this setting off based on their needs.

**Comment by Brian-Wuest** [comment]
This will be available in the next releases for 1.16.5 and 1.17.1.
