### ISSUE TITLE
Outdated Textures

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#205]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.14+
1. What type of issue is this? Choose one of the following:
    1. **Enhancement** (Add/Change something)
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details:

Some of the items, like `bunch_of_potatoes`, `bunch_of_beets`,  `bunch_of_carrots`, etc. are using outdated (pre 1.14) item textures, on 1.14 and above.

**Comment by Brian-Wuest** [comment]
I can see making the changes for things like the crates but not necessarily the bunches. Most of the food item is covered up in the texture so that's less of a problem.
