### ISSUE TITLE
[Bug]: Swift Blade Crafting Recipes

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#209]
### Minecraft Version

1.17.1

### Forge Version

Fabric

### Mod Version

Latest (2.1.1)

### Details

<img width="331" alt="" src="https://user-images.githubusercontent.com/27054231/129923638-22d382ce-b7eb-4215-b287-ac3315b69f25.png">
<img width="331" alt="" src="https://user-images.githubusercontent.com/27054231/129923648-9b8dfea3-fdec-4533-bfa3-aaa3eb889ebf.png">

Self-explanatory

**Comment by Brian-Wuest** [comment]
Closing as this is specific to the Fabric version of this mod.
