### ISSUE TITLE
[Enhancement]: Config to remove Swift Blades and Sickles

### ISSUE THREAD

**Issue by aaronhowser1** [Brian-Wuest/MC-Prefab#210]
### Minecraft Version

1.16.5

### Forge Version

36.2.2

### Mod Version

prefab-1.6.5.8

### Details

Honestly, I don't like Swift Blades and Sickles. I feel like they're outside the mod's scope. I have the recipes disabled, but I want to remove them from Prefab chests too.

**Comment by Brian-Wuest** [comment]
@aaronhowser1 We are working on this and will be in the next update for 1.16.5.

In addition we are making them less OP by reducing their damage by 1 and speed to 4.5 (normal sword speed is 1.6)
