### ISSUE TITLE
[Enhancement]: New Structure Item: Farms

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#218]
### Minecraft Version

-

### Forge Version

-

### Mod Version

Latest

### Details

# Farms
I suggest adding a new structure item, which will have multiple structure options: Farms. The name can be changed. The Farms item, and the Advanced Farms item will have farms!

The Farms item will be able to provide a wide variety of new structures to Prefab, and will make the mod more useful in Survival mode. 

## Categorization
 If the farm works automatically, without player doing something - that is Advanced Farms.
If the farm requires player doing something for the farm to actually produce resources - that is Farms. 

## Merging
I also suggest merging existing farm items into the new Farms item.
| Existing Item | Farms Item |
| --- | --- |
| Chicken Coop | Farms |
| Monster Masher | Advanced Farms |
| Sugar Cane Farm | Advanced Farms |
| Advanced Chicken Coop | Advanced Farms |
| Produce Farm | ! This structure needs changes |

## Structures
I can provide some of the structures for the Farms items, if the idea will be approved. 

# Modern Farms (?)
A new Modern structures item! That will have Modern "Farms" - Factories. 

If the Modern Farms item will be added, then the categorization of Farms will change:
Small farms that require players to produce resources - Farms
Medium to Large farms that require players to produce resources - Advanced Farms
Farms that do not require players to produce resources - Modern Farms

That will allow the merging of the `Produce Farm` without any changes to the Advanced Farms item, but on the other hand it might be a bit too much farms.

# Crafting Recipes
That is my idea on the crafting recipe. That can be changed.

| Farms | Advanced Farms | Modern Farms |
| --- | --- | --- |
| <img width="129" alt="" src="https://user-images.githubusercontent.com/27054231/131252063-8b9b5f9b-d9ad-4b84-95d3-ea6b55ac5e93.png"> | <img width="129" alt="" src="https://user-images.githubusercontent.com/27054231/131252072-0ef8ecb7-c0c6-4135-b477-8d035545dc82.png"> | <img width="129" alt="" src="https://user-images.githubusercontent.com/27054231/131252078-cb066e71-5330-4b1f-b942-2ec7ad708749.png">

**Comment by Brian-Wuest** [comment]
We will have tree tiers of "Farms"
Starter Farm
Moderate Farm
Advanced Farm

This is consistent with how we have been naming the Starter and Moderate house items.
The designation of a farm to a particular Tier is based on Size as well as complexity.


| Structure Name | Farm Tier |
|----------------|-----------|
Abandoned Mushroom Farm (New) | Starter
Beef Farm (New) | Starter
Berry Farm (New) | Starter
Cactus Farm (New) | Starter
Chicken Coop | Starter
Horse Stable | Starter
Stepped Farm (New) | Starter
Multi-Level Farm (New) | Starter
Rabbit Hutch (New) | Starter
Automated Chicken Coop | Moderate
Automated Farm (New) | Moderate
Fish Pond | Moderate
Bee Farm (New) | Moderate
Sugar Cane Farm  | Moderate
Automated Bamboo Farm | Advanced
Automated Bee Farm (New) | Advanced
Automated Melon Farm (New) | Advanced
Barn | Advanced
Green House | Advanced
Large Horse Stable | Advanced
Monster Masher | Advanced
Produce Farm | Advanced
Tree Farm | Advanced

**Comment by Dqu1J** [comment]
Is implemented in Fabric 1.17.1, and will be soon released on Forge.
