### ISSUE TITLE
[Enhancement]: Add missing brick and lumber bulk storage as placeable decor blocks

### ISSUE THREAD

**Issue by Syndaryl** [Brian-Wuest/MC-Prefab#224]
### Minecraft Version

1.17.1

### Forge Version

Forge 37.0.97

### Mod Version

1.17.1

### Details

The icons for the bulk storage blocks for bricks and log look very good, and would make good decorative items around an appropriately themed build. I'd love to have them as actual placeable blocks :)

**Comment by Dqu1J** [comment]
In addition to that, I'd love if the crates would be placeable too. Would make a nice decoration for some of the builds.
