### ISSUE TITLE
[Enhancement]: Customization of the Modern style starter home color palette

### ISSUE THREAD

**Issue by Syndaryl** [Brian-Wuest/MC-Prefab#225]
### Minecraft Version

1.17.1

### Forge Version

Forge 37.0.97

### Mod Version

1.17.1.1

### Details

The ability to change the dark blue blocks to other colors of carpet/concrete would be a nice touch. Greys for the folks trying to appease their community association, magenta for people trying to stand out, whatever :)

**Comment by Brian-Wuest** [comment]
This is something we will not be doing.

Modifying the prefabs in this way is hard to do as they are static "things" and trying to adjust small parts during building are maintenance intensive.

We try to limit this to as small as possible to very specific blocks (Glass and Beds for example).
