### ISSUE TITLE
Add/Design new light source block

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#23]
Having glowstone be the main light source for most buildings puts a gate on these buildings as the player has to get to the Nether first and with Glowstone being such a limited resource (in most vanilla and even modded worlds). We need a better resource.

**Comment by IamAlathe** [comment]
Blocks in Vanilla which produce light and can be acquired in the overworld:  Sea lanterns (still rather more late game, I'd think, as taking on an Ocean Monument is not very easy), Redstone (Mineable, only requires Iron), Lava (maybe combined with glass to make a solid block a feasible idea? But that would require a new block, I think.  Could be cool, though.), fire/torches.  If creating new blocks is not off the table, maybe something with wood, coal/charcoal for torch-like or torches and glass for lanterns?  You probably already have great ideas you're running with.  I'm excited to see what comes out!  😄

**Comment by Brian-Wuest** [comment]
Thanks at least for the ideas. And I should have updated this issue with what we were thinking.

Right now the paper lantern requires a torch, a piece of paper and a stick. It emits the same amount of light as a torch be can be placed anywhere and doesnt break when in water. It does take up a full block so you cannot use it as a quick air source.

You can see though the lantern as we have a specially designed model for it. There are screen shots of the block in action on the curseforge site in the screenshots of the machinery tower in the main description.

**Comment by Brian-Wuest** [comment]
This has been provided in Minecraft version 1.10.2 in version 1.1.1.8 which will be approved on curseforge shortly.

Minecraft 1.11 will be updated in a few days.

Closing this issue.

**Comment by IamAlathe** [comment]
I just wanted to say that I love the paper lanterns!

**Comment by Brian-Wuest** [comment]
Thanks!
