### ISSUE TITLE
[Enhancement]: Balancing Swift Blades & Sickles

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#234]
### Minecraft Version

1.16.5

### Forge Version

36.2.0

### Mod Version

1.6.5.13-pre-release

### Details

Swift Blades and Sickles aren't balanced. Swift Blades are overpowered and Sickles are underpowered. I suggest changing their stats to make them much more balanced and useful in combat:

### Swift Blades
| Tier | Attack Speed | Attack Damage |
| --- | --- | --- |
| Wood | 2.4 | 3 |
| Stone | 2.4 | 4 |
| Iron | 2.5 | 5 |
| Gold | 2.6 | 3 |
| Diamond | 2.6 | 6 |
| Netherite | 2.6 | 7 |

### Sickles
| Tier | Attack Speed | Attack Damage |
| --- | --- | --- |
| Wood | 1 | 1 |
| Stone | 2 | 2 |
| Iron | 3 | 3 |
| Gold | 1 | 1 |
| Diamond | 4 | 4 |
| Netherite | 4 | 5 |

**Comment by Brian-Wuest** [comment]
This won't be done. 
I like the way the swords are for their speed/damage as well as how the sickles work.
