### ISSUE TITLE
[Bug]: Can't place prefabs on server

### ISSUE THREAD

**Issue by Ian1141** [Brian-Wuest/MC-Prefab#238]
### Minecraft Version

1.17.1

### Forge Version

37.0.108

### Mod Version

1.7.1.1

### Details

When I try to place down a structure nothing happens

**Comment by Chaos1141** [comment]
It looks like the building files did not download, after reverting to 1.7.1.0 the files appeared

**Comment by Brian-Wuest** [comment]
This is not helpful. 

We need logs, mods lists and configuration settings.

**Comment by Ian1141** [comment]
I restarted my pc and changed some other mods around, I don't think it was prefab
