### ISSUE TITLE
[Bug]: Bulldozer no longer drops resources

### ISSUE THREAD

**Issue by smbarbour** [Brian-Wuest/MC-Prefab#241]
### Minecraft Version

1.16.5

### Forge Version

36.2.19

### Mod Version

1.6.5.13

### Details

On a previous modpack, the drops would appear when using the bulldozer.  On the current modpack with the version listed above, the drops do not appear.  I have confirmed that the config setting to allow drops from the bulldozer:

"Bulldozer Creates Drops" = true

**Comment by Brian-Wuest** [comment]
If you're in creative mode it will not drop resources regardless of the type of bulldozer used or configuration setting.

**Comment by smbarbour** [comment]
This is in survival mode.
