### ISSUE TITLE
[Bug]: Monster Masher Missing?

### ISSUE THREAD

**Issue by Vercalos** [Brian-Wuest/MC-Prefab#246]
### Minecraft Version

1.16.5

### Forge Version

36.2.8

### Mod Version

1.6.5.14

### Details

I don't know what causing it, as I don't see any config options in the TOML file for the building outside of enabling or disabling the spawners within it, but the Monster Masher building seems to be missing from my installation of this mod.  Seeing as I _just_ installed it and didn't make any changes to any config files, and the latest changelog mentions it, I'm not sure _what_ happened.

**Comment by Brian-Wuest** [comment]
The Monster Masher is available in the "Advanced Farm" item.

**Comment by Vercalos** [comment]
Oops. Sorry.  I'm used to the old version of the mod where it was a separate item.
