### ISSUE TITLE
A few feature Idea's

### ISSUE THREAD

**Issue by JzJad** [Brian-Wuest/MC-Prefab#25]
Adding mod specific structures for when a mod is present, example a Pam's craft Kitchen house.
Also adding a table to change the majority of blocks used in the schematics, having the player fill an inventory of the exact number of blocks needed.

**Comment by Brian-Wuest** [comment]
I could definitely see mod-specific structures (which are only available if the dependent mod is registered).

Can you expand on what you mean by this:

> Also adding a table to change the majority of blocks used in the schematics, having the player fill an inventory of the exact number of blocks needed.

**Comment by JzJad** [comment]
For instance the warehouse uses vanilla chests, why not have a block that allows replacing the vanilla chests with say Iron Chest's assuming the player has enough to swap out. Or even maybe even being able to modify structure blocks like slabs, andesite, etc Whilst its still a blueprint.

**Comment by JzJad** [comment]
In other words a crafting table/block of sorts that allows to customize the blocks used in the spawning/building process as long as the player has enough blocks to substitute for.

**Comment by Brian-Wuest** [comment]
Alright, I can see that working. Kaojiin and I can talk about it. But it seems pretty feasible and less prone to duplication like the player created structures request.

**Comment by JzJad** [comment]
Yeah as long as editing requires the actual number of blocks needed for the structure I'm sure other mod packs like my own would love to keep it around!

**Comment by Brian-Wuest** [comment]
I am closing this item, we have been working on new structures and don't have plans to do this feature at this time. If we get to this later it will be re-opened.
