### ISSUE TITLE
[Enhancement] NEW Blueprint Crafting System

### ISSUE THREAD

**Issue by Dqu1J** [Brian-Wuest/MC-Prefab#251]
### Minecraft Version

1.18.1

### Forge Version

Forge

### Mod Version

dd98bd0

### Details

# What?
A new blueprint crafting system, which will require blueprints to be crafted on a new special block called `Drafting Table`. This new system would be the default, but with the possibility to toggle it back to the current one in the config. As the current recipes don't require 100% of the structures resources from the player, there would be a new config value called `cost-percentage`, which will be set to 75-80% by default. It determines the percentage of the blocks that the player needs to input to the Drafting Table in order to craft the blueprint. If the modpack developer wants to override that value for a specific structure, they can set it in the `cost-percentage-overrides` property. 

# Why?
The current system isn't balanced well. It requires creating new recipes manually, and it is tough to make them balanced.  It also makes some of the modpack developers afraid because of the fact that the current system requires less resources to produce the structure than the actual structure includes.

The new system wouldn't have those issues, with each recipe generating dynamically, and with possibility for modpack developers to configure each structures cost to their liking. The new system may also get rid of the compressed materials, as they won't longer be needed. 

This system was also considered on the early stages of Prefab, but it was decided by the developers to not implement it because of the lack of knowledge at that time. Now, this have changed, and we have a possibility to implement that into the mod.

# Problems!

### Blueprints with multiple styles
The most major problems of all. Blueprints which include multiple structures in them destroy the whole idea of the new crafting system, and I have no idea on how to solve that problem.

### Inputting materials
How to do it right? I don't know. Inputting it via an external container, like a chest, that is placed next to the Drafting Table sounds like the most safest option, as we don't have to handle storing all the items, inputting them, and etc.   

# What I think about this
This is a major change. It will be hard to implement, but in my opinion this is going to make the mod much better and much more balanced. Things outlined in `Possible Problems` are going to be really difficult to solve, and will maybe require changing other aspects of Prefab. I consider this change as a low priority.

I'd also add an item called `Blank Blueprint`, which will be required to be placed directly into the Drafting Table and will act as one of the crafting ingredients. It would be crafted using 3 dried kelp placed horizontally in a crafting table. Why? Just seems logical and nice to have. 

# Checklist:
Checklist of needed things for this to be added

- [ ] Solve the multiple styles problem
- [ ] Drafting Table and it's GUI
- [ ] Calculating the amount of materials in the structure
- [ ] Cost Percentage
- [ ] Toggle between old and new crafting systems in the config
- [ ] Inputting materials to the Drafting Table
- [ ] Crafting blueprints on the Drafting Table

**Comment by Brian-Wuest** [comment]
Removing in favor of #257 .
