### ISSUE TITLE
[Bug]: Clientside preview crash

### ISSUE THREAD

**Issue by Dryxen** [Brian-Wuest/MC-Prefab#252]
### Minecraft Version

1.18.1

### Forge Version

39.0.63

### Mod Version

1.8.1.1

### Details

Client Side crash when trying to preview structures with a starter house.
Crash Log:
 https://pastebin.com/Z8nA6KJZ
Lastest log snippet:
https://pastebin.com/4P3xz9ti

**Comment by Brian-Wuest** [comment]
Looks like the only way you could get this is if you're a player that's blocked from sending or receiving chats.

Not going to make a fix/work around for that.
