### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TBout0** [Brian-Wuest/MC-Prefab#254]
### Minecraft Version

1.18.1

### Forge Version

fabric-loader-0.12.12-1.18.1/fabric/Fabric

### Mod Version

v3.0.1

### Details

When any shaders are enabled, previews of buildings are not visible.

**Comment by Brian-Wuest** [comment]
1. This is the wrong repository for the bug.
2. You didn't provide a title.
3. For shaders you typically have to use something like optifine, we don't support that mod or similar mods due how much they interfere with this type of code.
