### ISSUE TITLE
[Bug]: Crash with Moderate Modern House

### ISSUE THREAD

**Issue by Darkfiend009** [Brian-Wuest/MC-Prefab#255]
### Minecraft Version

1.18.1

### Forge Version

39.0.63

### Mod Version

1.8.1.2

### Details

Crashing occurs when placing the Moderate Home with the Modern type selected. Previewing the Moderate Modern House works fine. Other moderate house types work without issue. Other modern versions seem to work without issue too.

Crash Report: https://pastebin.com/T6k2pZvW

EDIT:
After some additional testing, these other Modern versions are also crashing with an identical crash report:

Basic Modern Cottage, Basic Modern Hotel, Basic Modern Restaurant, Basic Modern Juice Shop.

The Basic Modern Cinema and Fruit Stand do not crash.

**Comment by Brian-Wuest** [comment]
Thank you for the detailed report.

That'll learn me from trusting my ports from fabric! 😢
