### ISSUE TITLE
Disable previewing 1.10.2 - 1.11.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Brian-Wuest/MC-Prefab#26]
So I have now realized you should add a way to disable previews. The Bridgemod is great but it has a ticking entity leak with some mods.

**Comment by Brian-Wuest** [comment]
Can you explain what you mean by "ticking entity leak"?

Is it causing slow downs when rendering or is something else going on?

For that item I didnt want to make a gui like with the others since it was a very simple structure.

**Comment by P3rf3ctXZer0** [comment]
With Shaders and Certain mod combinations we crash

**Comment by Brian-Wuest** [comment]
Hmmm. Can you provide a crash log? This way I can see if I can address the issue instead of disabling the feature.

Also, I am curious on if this is a problem with the Botania Preview feature for those structures since it's mostly the same code. Would you be willing to check?

**Comment by P3rf3ctXZer0** [comment]
Yeah if it crashes again. Still it might be a good idea. I am sure this is not the last you have heard of this type of issue.

**Comment by Brian-Wuest** [comment]
You are probably right about that 😄. I have fixed a few issues already due to other mods causing issues with the preview functionality.

That's the risk when you do this kind of stuff. Though with this particular feature I think it's incredibly useful for the players that use this mod.

**Comment by P3rf3ctXZer0** [comment]
@Brian-Wuest yes I agree completely.

**Comment by IamAlathe** [comment]
I like the preview option.  I'm really good at placing my buildings wrong, then I'm left with nothing but to cuss about it when I destroy half my garden.  I once destroyed half of my Tinker's Smeltry.  But I'm all for options, so having the option to disable it is good, especially if it's causing issues.  😃

**Comment by Brian-Wuest** [comment]
I am working on the option to disable the preview functionality for all structures and the instant bridge. This will be pushed with the Defense Bunker structure.

**Comment by Brian-Wuest** [comment]
The ability to disable the Preview Functionality has been released with version 1.1.1.9 for minecraft 1.10.2 and will be forwarded to 1.11.2.

Closing this for now.
