### ISSUE TITLE
[Bug]: Glass slab & stairs missing a loot table

### ISSUE THREAD

**Issue by WenXin20** [Brian-Wuest/MC-Prefab#260]
### Minecraft Version

`v1.18.1`

### Forge Version

`v39.1.2`

### Mod Version

`v1.8.1.4`

### Details

The glass slab & stair is missing a loot table and doesn't drop when mined with silk touch. 

Some blocks are also missing the new block tags `minecraft:mineable/pickaxe`, etc.

**Comment by Brian-Wuest** [comment]
1.18.1 is no longer supported, please update to 1.18.2 and check again.

**Comment by WenXin20** [comment]
Some of my mods have not yet updated to 1.18.2, but I have checked the prefab file for 1.18.2 and it is also missing the loot table files for glass blocks.
