### ISSUE TITLE
it doesn't build nothing on servers.

### ISSUE THREAD

**Issue by ciospettw** [Brian-Wuest/MC-Prefab#261]
### Minecraft Version

1.18.2

### Forge Version

1.18.2

### Mod Version

1.8.2.0

### Details

When i try to build something in a server, nothing happens.
i tryed in creative on a noraml word (Not a server) And it works, so is Prefab supported in servers and do i have to install some plugins/mods in it to make it work?

**Comment by Brian-Wuest** [comment]
The server and client both need to have prefab included.

**Comment by Brian-Wuest** [comment]
Please use the discord server for questions or troubleshooting.
