### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by GrayStriped** [Brian-Wuest/MC-Prefab#262]
### Minecraft Version

1.18.2

### Forge Version

Fabric 1.13.3

### Mod Version

3.1.3

### Details

Game crashed while attempting to place down the Tower Moderate House, and had generated about half of the house upon reloading the world.

Crash report here: https://pastebin.com/cmxwf7KR

**Comment by Brian-Wuest** [comment]
Unable to duplicate even on CurseForge custom mod pack.

Make sure you have the correct Fabric API version installed (50.0 or 51.1).

Additionally; this is not the Prefab-Fabric repository.
