### ISSUE TITLE
[Enhancement]: Config options for starter house houses

### ISSUE THREAD

**Issue by itsdinkd** [Brian-Wuest/MC-Prefab#263]
### Minecraft Version

1.182

### Mod Version

latest

### Details

Hoping to see if theres a way you can add in options into the config to disable/enable some of the new starter house options that were added in for 1.18.2. The tree house for example in my opinion is not a starter house, its more of a farm, and I would love to ability to disable it for my modpack, as well as a couple others like the tower.

**Comment by Brian-Wuest** [comment]
Thank you for this entry. This is a great idea to add to the mod. 

I cannot promise when this will be done however as I would want the players/server owners to turn off options for all items which have options (which is a LOT of them).

That said we are in the middle of a fairly large project right now and have limited time for development. This other project takes priority over other things except for critical bugs.

**Comment by itsdinkd** [comment]
completely understood! also, I apologize i meant to make this for the fabric mod, however, its not a bad thing to suggest for the forge version either.

**Comment by Brian-Wuest** [comment]
This will be released for Fabric and Forge 1.19.2 in the next release of Prefab/Prefab-Fabric.

We do not have a date for this at this time, but I hope it will be soon.

**Comment by Brian-Wuest** [comment]
Closing issue as this will be released when 1.19.2 is ready.
