### ISSUE TITLE
[Enhancement]: 

### ISSUE THREAD

**Issue by ghost** [Brian-Wuest/MC-Prefab#264]
### Minecraft Version

1.18.2

### Forge Version

40.1

### Mod Version

1.8.2.2

### Details

I would like to see a place to brew potions added to the workshop.

**Comment by Brian-Wuest** [comment]
We will not add this modification to the workshop as there is a lot going on in there already.

These buildings are not expected to provide every need.

If you want some tool or functionality, you can always craft the block and place it where you want.

**Comment by ghost** [comment]
THen you should remove brewing stands from the upgrade recipe
