### ISSUE TITLE
[Bug]: Several Structures have missing things / issues

### ISSUE THREAD

**Issue by amberroseymc** [Brian-Wuest/MC-Prefab#265]
### Minecraft Version

1.18.2

### Forge Version

40.1.68

### Mod Version

1.8.2.2

### Details

Tower Starter base tools end up in furnace due to them being in the barrel above it

Cabin Starter home missing tools

Tower Moderate has snow and moss under it in basement

**Comment by amberroseymc** [comment]
![image](https://user-images.githubusercontent.com/45043402/183377058-353c9d73-8463-4e79-8dd8-1a95832763a9.png)
Moderate Tower With Moss and Ect 

Tools in Furnace (Tower Starter)
![image](https://user-images.githubusercontent.com/45043402/183377379-e6a5518f-9622-4292-9ced-26a69f4ed5de.png)
![image](https://user-images.githubusercontent.com/45043402/183377399-13d40c1c-fef5-4dd7-9b82-033a826d6deb.png)
![image](https://user-images.githubusercontent.com/45043402/183377417-3b75e30e-3e95-4003-aabd-cf0dc3c46d56.png)

**Comment by Brian-Wuest** [comment]
Response to each bug described.

1. We don't specify which chest/barrel the starting items go into so it's completely random. We are also not going force the items to go to a certain spot or force people to design the buildings a certain way. 
    1. Even if you find that it's going to the same place for you, it will be in a different place for a different player or build direction.
2. What's the problem with the moss/snow/glow-ivy at the bottom of the moderate tower? Not every building can or should be absolutely perfect and maybe was a design intention by the designer.
3. For the Cabin starter missing tools, we only provide tools/items for the first starter/moderate house built in a world for a player. So, if you already built a house in that world then you won't get the tools again.

**Comment by amberroseymc** [comment]
> Response to each bug described.
> 
> 1. We don't specify which chest/barrel the starting items go into so it's completely random. We are also not going force the items to go to a certain spot or force people to design the buildings a certain way.
>    
>    1. Even if you find that it's going to the same place for you, it will be in a different place for a different player or build direction.
> 2. What's the problem with the moss/snow/glow-ivy at the bottom of the moderate tower? Not every building can or should be absolutely perfect and maybe was a design intention by the designer.
> 3. For the Cabin starter missing tools, we only provide tools/items for the first starter/moderate house built in a world for a player. So, if you already built a house in that world then you won't get the tools again.

for the third one my friend placed it down as there first one

**Comment by Brian-Wuest** [comment]
Figured out where the items are being generated. It looks like there are some hidden barrels on the second floor in the design.

They are hidden behind some of the logs on the second floor. Screen shots below.

Before breaking the logs
![2022-08-09_05 58 09](https://user-images.githubusercontent.com/13502068/183632028-8db93c13-4d35-4b72-9dc0-accb45a69de3.png)

After breaking the logs
![2022-08-09_05 58 21](https://user-images.githubusercontent.com/13502068/183632061-245e487b-dce7-4c93-80e9-8d4191422eec.png)

I will push out an update later in the week which contains a re-scan of this building to remove the hidden barrels.

Thank you for reporting this issue!

**Comment by Brian-Wuest** [comment]
This was fixed in 1.8.2.3.
