### ISSUE TITLE
[Enhancement]: 1.19.2 Version needs to exist.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Brian-Wuest/MC-Prefab#267]
### Minecraft Version

1.19.2

### Forge Version

1.19.2 - 43.1.1

### Mod Version

1.19.2

### Details

Please make it exist as mods like 'no chat report and no telemetry make 1.19.2 a safe environment'

https://www.curseforge.com/minecraft/mc-mods/no-chat-reports

https://www.curseforge.com/minecraft/mc-mods/no-telemetry

**Comment by Brian-Wuest** [comment]
1. We have no idea what you are even asking for
2. We are not going to try and work around Mojang's protections so don't bother asking.
3. If this is a round-about way to get us to release a version for 1.19.2, don't, we are working on it.
