### ISSUE TITLE
[Bug]: Crash on Server Start

### ISSUE THREAD

**Issue by waddon1** [Brian-Wuest/MC-Prefab#268]
### Minecraft Version

1.19.2

### Forge Version

43.1.24

### Mod Version

1.9.2.0

### Details

The mod crashes on server start https://pastebin.com/1mZXmc0U

**Comment by Brian-Wuest** [comment]
Fixed, will be available soon on CurseForge

**Comment by waddon1** [comment]
This is still happening on 1.9.2.1
