### ISSUE TITLE
[Bug]: When i put this mod into my Minecraft server, when i run it says 'unexpected error'

### ISSUE THREAD

**Issue by Dom202000** [Brian-Wuest/MC-Prefab#269]
### Minecraft Version

1.19.2

### Forge Version

1.19.2

### Mod Version

1.19.2

### Details

So i love this mod so i put it into my minecraft server but when i start it says 'unexpected error' but when i remove it, it works 
Anyone Help???!

**Comment by Brian-Wuest** [comment]
Fixed, will be available on CurseForge soon.
