### ISSUE TITLE
Thought/request:  Mine Entrance

### ISSUE THREAD

**Issue by IamAlathe** [Brian-Wuest/MC-Prefab#27]
Having played with this for a while now, I find that one of the best features of the starter house is the mine shaft.  If I wanted to be able to make the starter house blueprint, it would be to sink another mine shaft somewhere.  Wondering if that's what's behind some of the requests for such a blueprint lead me to wonder if it would be feasible to create a "Miner's Hut" or "Mine Entrance" or some such.  (I've been terribly sick for most of a week, my naming capabilities are shot right now.)  Lately, I use the starter house for just that purpose, and as a spot just until I build something else.

My thoughts on what such a build would need:
*Mine shaft (obviously) The same convention currently used in the starter house should work just fine.
*Safe place above ground.  No one wants to come out of the mine and get mobbed by hostile mobs.
*Storage.  You may want to keep that cobble, but not haul it all home right now.
*Crafting bench.  For making new pickaxes.
*Furnace.  Let it smelt while you mine.
*Bed.  Temporarily set your spawn in case of accidents or quickly pass the night so you can trek home with your loot.

So yes, very similar to the starter house, but with different config options (or none).  But this place is utilitarian, a place to get your dig on.

**Comment by Brian-Wuest** [comment]
I really like this idea!

Since its not the starter house, I am thinking that it should not gather the cobblestone or stone when making the mineshaft. It would gather everything else.

Recipe wise. I am thinking 2 iron picks, 2 compressed stone a bed and 4 piles of timber.

**Comment by IamAlathe** [comment]
I like!  I agree about the stone and cobble.  I like the 2 iron picks, after all, if you can't make those yet, you don't need a second mine!  😄 Can't wait to see how it comes out!

**Comment by Brian-Wuest** [comment]
This has been released with version 1.1.1.9 for minecraft 1.10.2 and will be forwarded to 1.11.2.
