### ISSUE TITLE
[Bug]: Server crash on startup

### ISSUE THREAD

**Issue by waddon1** [Brian-Wuest/MC-Prefab#270]
### Minecraft Version

1.19.2

### Forge Version

43.1.25

### Mod Version

1.9.2.1

### Details

Same crash like before on startup, but on the new version even though you fixed it? https://pastebin.com/1mZXmc0U

**Comment by Brian-Wuest** [comment]
This will take a bit to figure out, I have errands to run this morning and the error message doesn't provide a lot of context to where the problem actually resides.

**Comment by Brian-Wuest** [comment]
Figured out the issue. Forge required another setting to not do client events on dedicated servers. They didn't require that before so it was missed.

**Comment by Brian-Wuest** [comment]
This will be fixed in 1.9.2.2 which is being uploaded/approved by curseforge right now.

Thank you for reporting this.
