### ISSUE TITLE
[Enhancement]: Underground Mining shack/lodge

### ISSUE THREAD

**Issue by kwpugh** [Brian-Wuest/MC-Prefab#271]
### Details

I would like to suggest a medium sized underground mining shack with furnaces, storage chests and campfires.  It would be a great addition to construct when mining deep underground.  I would suggest it being all on one level, no windows.

**Comment by Brian-Wuest** [comment]
That seems like a neat idea. The only concern I would be as a player actually. With how our structures are generated, any blocks in the affected area are destroyed and cannot be retrieved. This would mean that you could potentially miss out on valuable ores or other blocks. We are also not just going to allow our structures to capture such a large area of ores and provide for free. The mineshaft kind of does this (it's a bit game breaking) already and I don't want to extend that out to such a large potential area.

Thoughts?

**Comment by kwpugh** [comment]
I see what you mean, but as a player I would expect that the area where the structure is placed would be destroyed.  It is a trade off in my mind.

**Comment by Brian-Wuest** [comment]
Thank you, wanted to make sure. I cannot promise that this would be done anytime soon but we will keep this open.

Really like the idea!

**Comment by Brian-Wuest** [comment]
As cool as this would have been, this mod will no longer be maintained by the current team after March 31st and is as of right now in maintenance mode.
