### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rexzooly** [Brian-Wuest/MC-Prefab#274]
### Minecraft Version

1.16.5/1.19.2

### Forge Version

All

### Mod Version

All versions under the MC versions

### Details

I have a mod I am working on what sets a dimension via the json/datapack methered but problem is prefab always turns it's water in to cobblestone, the dimension has lets bed work and water does not vap but the template is end, so I was thinking it could be of this though water is aloud in the end.

What do you have in the mod that changes water to cobblestone, I have other schematics spawn in to the world what spwans water fine.

Mod:
https://www.curseforge.com/minecraft/mc-mods/docblocks

**Comment by Brian-Wuest** [comment]
There is a configuration setting to allow water in other dimensions but the overworld. However, we will never allow water in The Nether regardless of configuration setting. So if the Biome matches The Nether it will never work.

**Comment by rexzooly** [comment]
> There is a configuration setting to allow water in other dimensions but the overworld. However, we will never allow water in The Nether regardless of configuration setting. So if the Biome matches The Nether it will never work.

Is there away for us to define that as a mod creator or do we need to add that to a FAQ for modpack creators?
thanks for the reply and I am using the End noise settings over Nether so sounds like it should be OK.

**Comment by Brian-Wuest** [comment]
It would have to be a FAQ for any mod pack creators sorry.
