### ISSUE TITLE
[Bug]: Config doesn't save starter house preference

### ISSUE THREAD

**Issue by katubug** [Brian-Wuest/MC-Prefab#275]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Mod Version

1.8.2.3

### Details

I am trying to disable the starter house being given, but the config option doesn't seem to be saving, either done in game via Configured, or done through the config toml.

**Comment by Brian-Wuest** [comment]
Works for me locally.

As stated in the FAQ in our Discord server and the comment generated with the configuration file. You have to set it to "Nothing". Casing is important.


![image](https://user-images.githubusercontent.com/13502068/198891458-d40b348e-3650-4794-895c-145b8442dfb4.png)

**Comment by katubug** [comment]
https://i.imgur.com/441MLh0.png

I am aware. It kept resetting regardless. At the very least, the ingame version does not stick. So far this time editing the toml file directly seems to have worked at least! So it's possible the issue is with Configured rather than this mod, or maybe I forgot to save the file last time or something, idk. Thanks for your time!

**Comment by Brian-Wuest** [comment]
I don't know how configured works so not sure what the problem could be. But we have our own gui for mod setting configuration so configured must be overriding ours.

**Comment by markygnlg** [comment]
> I am aware. It kept resetting regardless. At the very least, the ingame version does not stick. So far this time editing the toml file directly seems to have worked at least! So it's possible the issue is with Configured rather than this mod, or maybe I forgot to save the file last time or something, idk. Thanks for your time!

TL:DR
 - some mods update immediately when settings are edited;
 - some mods require the savegame to be reloaded (ie. quit to main menu, edit the settings & then load the savegame);
 - some mods require minecraft to be exited/quit completely (edit the file after mc has completely exited).

Just a heads up - Configured (by MrCrayfish?) can only edit mods that check the current memory or check the memory after re-loading a save or starting a new game. Some mods require minecraft to quit & be restarted.

... ie. JEI will update immediately when you edit settings by either:
(1.) using JEI's settings;
(2.) using Configured;
(3.) when its toml files are edited via a text editor while the game is running.

... if you use notepad++ you'll know which mod does what & when by the alert you get after a file has changed (ie. if you quit minecraft to the main menu [& the file you've edited & saved is still open within notepad++] you'll be informed if your changes have been reverted... same if you quit to desktop, that way you can tell which mod requires a complete minecraft restart, a savegame reload or just an instant memory edit)
