### ISSUE TITLE
[Enhancement]: 1.16.5 - Pixelmon is trapped on 1.16.5 do you mind porting the tower schematic or more to prefab mod for 1.16.5

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Brian-Wuest/MC-Prefab#277]
### Minecraft Version

1.16.5

### Mod Version

 prefab-1.6.5.16

### Details

1.16.5 - Pixelmon is trapped on 1.16.5 do you mind porting the tower schematic or more to prefab mod for 1.16.5?

**Comment by Brian-Wuest** [comment]
I am sorry, but we will be unable to backport any structures as 1.16.5 is not within our support window anymore.

We are a small team with jobs and families so we support what we can and that is only the most recent release and one back (so 1.19.2 and 1.18.2 at this time).
