### ISSUE TITLE
[Bug]: Monster Masher always contains Spawners

### ISSUE THREAD

**Issue by VanyaBaou** [Brian-Wuest/MC-Prefab#278]
### Minecraft Version

1.16.5

### Forge Version

1.16.5-forge-36.2.33

### Mod Version

prefab-1.6.5.15.jar

### Details

The Monster Masher prefab spawns with Mob Spawners, even with the config setting **Include Spawners in Monster Masher** set to **false**

**Comment by Brian-Wuest** [comment]
1.16.5 is no longer supported, please update to a modern version of Minecraft.

We only support a few versions due to time constraints on the development team.

**Comment by markygnlg** [comment]
> ### Mod Version
> prefab-1.6.5.15.jar
> 
> ### Details
> The Monster Masher prefab spawns with Mob Spawners, even with the config setting **Include Spawners in Monster Masher** set to **false**

If you're still playing on 1.16 you might want to try older versions of this mod. I suggest:
 - prefab-1.6.4.3
 - prefab-1.6.5.0
 - prefab-1.6.5.4
 
 ... more info [here @ issue 169](https://github.com/Brian-Wuest/MC-Prefab/issues/169)
