### ISSUE TITLE
[Bug]: prefab:item_mineshaft_entrance does not make a mineshaft

### ISSUE THREAD

**Issue by markygnlg** [Brian-Wuest/MC-Prefab#279]
### Minecraft Version

1.19.2

### Forge Version

43.1.7

### Mod Version

prefab-1.9.2.4

### Details

For the 1st time using your mod I set:

"Starting Item" = "Nothing"

I finally collected enuf resources to make a 'prefab:item_mineshaft_entrance' but there was no mineshaft.

I then used 'NBTExplorer v2.8.0' to give myself a few more 'prefab:item_mineshaft_entrance' & none of them built a mineshaft.

I then set:

"Starting Item" = "Starting House"

... it gave me the "Starting House" when I reloaded the savegame & it built the mineshaft (I used the 1st "Starting House").

**Comment by markygnlg** [comment]
by ' the 1st "Starting House" ' I meant the "Basic House" from 'prefab:item_house'

![image](https://user-images.githubusercontent.com/62978705/208219683-7219ff3b-da8b-46cc-ac77-a4933299b310.png)

**Comment by Brian-Wuest** [comment]
Thank you for finding this, apparently this has been a defect since August.

**Comment by Brian-Wuest** [comment]
This has been fixed with 1.9.2.5 which will be available on CurseForge when they release it.

**Comment by markygnlg** [comment]
That was a fast fix! Thanks. It's already up on curseforge.
