### ISSUE TITLE
[Bug]: The ladder is damaged after placing the building

### ISSUE THREAD

**Issue by 48004800** [Brian-Wuest/MC-Prefab#282]
### Minecraft Version

1.19.2

### Forge Version

43.2.3

### Mod Version

1.9.2.5

### Details

https://www.curseforge.com/minecraft/mc-mods/quark/files/4361476
Under the influence of quark 3.4-888, the ladder of many buildings will be damaged automatically if the player places the building

**Comment by Brian-Wuest** [comment]
Minecraft version 1.19.2 is no longer supported. 

Additionally, if another mod caused the bug with our mod, please create a bug report with them as we have never had an issue with Quark like this that I am aware of.
