### ISSUE TITLE
[Bug]: Mobs disappearing when placed in fish pond.

### ISSUE THREAD

**Issue by Kdschar** [Brian-Wuest/MC-Prefab#285]
### Minecraft Version

1.19.2

### Forge Version

43.2.4

### Mod Version

1.9.2.5

### Details

Hey there!

First of all I wanted to thank you for making such a wonderful mod! I struggle a lot with the structure building aspect of the game, and your mod has saved me _so much heartache_ when dealing with bases, so thank you for that!

Onto the bug:

I built a fish pond on my base and added a few mobs to it to liven it up. Some ranchu from the mod Baby Fat, a couple lobsters from Alex's Mobs, some koi and a dumbo octopus from Critters & Companions, and a tadpole from Mincraft itself. After leaving for a while and coming back, I noticed everything but the lobsters and ranchu were missing. I tried adding them back a couple times in creative mode, but they always wind up poofing. 

I'm dealing with a rather large modpack and know there's a high likelihood that it's not necessarily Prefab that's causing the issue, but I thought I'd start here. Any ideas? Thanks for your time!

**Comment by Brian-Wuest** [comment]
Once the structure is placed, any interactions are due to outside mods or vanilla functionality.

Additionally, the mod is no longer under active development nor supported by the old development team.
