### ISSUE TITLE
[Enhancement]:  Release houses and farms as schematic files

### ISSUE THREAD

**Issue by ChaosNicro** [Brian-Wuest/MC-Prefab#289]
### Details

With 1.20+ not getting support, it would be really nice to get a zip with all the structures (without modded blocks) as schematics. I really like the designs and they make starting out a lot more fun. I'd love to import them into something like schematica to still use them after this is sunsetted. I couldn't manage to extract them on my own.

**Comment by Brian-Wuest** [comment]
You can always generate the structures in a 1.19 world and then use another mod to scan them and replace the mod blocks with something else.

Otherwise, the zip files are in this repository for you to extract and work with.
