### ISSUE TITLE
Underwater base

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#29]
Create an item which will allow the user to generate an underwater structure.

The item will have to recognize that it can only be used when targeting water and that there is enough water around to house the structure (1 block of water isn't enough to house this structure).

It should have enough space to have a small house a small farm and tall enough for the player to grow some normal trees (like birch) under the glass.

The recipe will require Double Compressed Glass. This will be a new block which needs to be added to the mod. Compressed Glass will also be added which will be used to create the Double Compressed Glass.

**Comment by IamAlathe** [comment]
Oh my gosh, I've been thinking this for a while now.  I love underwater domes (and other structures), but they are such a pain to build with the having to make the structure then remove the water.  Perhaps the recipe should include something like a sponge, ostensibly for removing the water inside the structure?  Or wool or something if you don't want it to have the requirement of sponge-finding, which requires an Ocean Monument in Vanilla, IIRC.

**Comment by Brian-Wuest** [comment]
Might go with wool or something because I hate going after Ocean Monuments as the mobs around them are really hard to take out.

In order for players to not destroy these monuments I may put a check in for those unique blocks found in the monuments. A player could create a structure next to one but not actually destroy it.

Though they could destroy it by using existing structures but they would still be under water.

**Comment by IamAlathe** [comment]
I like the way you think!  The incredible pain of going after sponges is exactly why I was thinking something else to substitute.  I also really like the idea of setting some protections for a monument.  Could help with getting into a monument too.  Create a safe structure nearby to base yourself for going after it.  

Thought:  Diving Bell.  Top block created on water, giving an air space for working in the ocean.

**Comment by Brian-Wuest** [comment]
Our current recipe requires 1 Sea Lantern and Coil of Lanterns (81 Paper Lanterns total) but the resulting building uses Sea Lanterns as it's light source. So there are a ton of them.

Recipe currently being considered.
 xxx
 yzy
 yay
 
  x = Glass
  y = Double Compressed Stone
  z = Sea Lantern
  a = Coil of Lanterns

We may not require this building to be made underwater but is designed to work well underwater.

**Comment by IamAlathe** [comment]
Sounds interesting!  Octagonal and very tall, what kind of dimensions are we looking at here?  I like the idea of making it octagonal.  It's a less common shape for Minecraft builds.  Also, when you say Glass, do you mean Double Compressed Glass, as you referenced in your first post?  I'm excited!

**Comment by Brian-Wuest** [comment]
Here are some pictures I took since I an not describing this very well.

http://imgur.com/a/LdTOc

This is more or less the final design and will most likely be out next week.

**Comment by Brian-Wuest** [comment]
This has been implemented in version 1.1.1.11 for Minecraft 1.10.2 and 1.2.0.6 for Minecraft 1.11.2.

These are available on curseforge.
