### ISSUE TITLE
Prefab for 1.20.1 with Forge 47.2.1

### ISSUE THREAD

**Issue by gawamaster** [Brian-Wuest/MC-Prefab#290]
### Minecraft Version

1.20.1

### Forge Version

47.2.1

### Details

HI.  I love prefab!  I started playing minecraft 1.20.1 and I would really love to have your Prefab for it.  Will you be making a 1.20.1 version?  Thank you.  Jason

**Comment by Brian-Wuest** [comment]
This mod is no longer in active development so it will not be updated to the latest version of minecraft.

**Comment by Brian-Wuest** [comment]
FYI - We have released a 1.20.6 Forge and Fabric release, please check it out.

We are back!
