### ISSUE TITLE
[Enhancement]: Update to 1.20

### ISSUE THREAD

**Issue by Ben-Shing** [Brian-Wuest/MC-Prefab#291]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Details

Please update to minecraft 1.20

**Comment by kaojinn** [comment]
Active development on this mod ended in March of last year.  A new coder has taken over, but they aren't using this GitHub project for it, and they currently only have a working Fabric version.

**Comment by Brian-Wuest** [comment]
FYI - We have released a 1.20.6 Forge and Fabric release, please check it out.

We are back!
