### ISSUE TITLE
[Bug]: house 1 dupe everytime i rejoin my server

### ISSUE THREAD

**Issue by VaporeonScripts** [Brian-Wuest/MC-Prefab#296]
### Minecraft Version

1.21.1

### Forge Version

Neoforge .80

### Mod Version

latest

### Details

it dupes for every server join

**Comment by Brian-Wuest** [comment]
Found the issue, the Save/Load player data mixin wasn't registered correctly for servers. This has been addressed. Will be uploading to CurseForge.
