### ISSUE TITLE
[Bug]: server crash due to prefab

### ISSUE THREAD

**Issue by VaporeonScripts** [Brian-Wuest/MC-Prefab#297]
### Minecraft Version

1.21.1

### Forge Version

Neoforge .83

### Mod Version

latest

### Details

https://mclo.gs/iJ0YAPF
https://mclo.gs/eGBX0IL

**Comment by VaporeonScripts** [comment]
a neoforge dc server member said this: "Prefab did something weird with a recipe ingredient."

**Comment by Brian-Wuest** [comment]
You will have to provide your prefab server config so I can attempt to duplicate the issue as you may have some recipes disabled.

I would also like your client side Prefab config file for comparison sake as well for full environment comparison.

**Comment by VaporeonScripts** [comment]
here u go 
https://mclo.gs/fnyPW76

**Comment by Brian-Wuest** [comment]
Hmmm, looks like you didn't turn anything off in the server config. What about the client config?

**Comment by VaporeonScripts** [comment]
thats the only config i got
![image](https://github.com/user-attachments/assets/41ac6f42-07d0-442e-8a27-4dd44f7079eb)

**Comment by VaporeonScripts** [comment]
issue happened once again ,its frustating, just host a server with neoforge on ur machine with the mod installed, u will see the crash ig

**Comment by VaporeonScripts** [comment]
other than the fact that u should generate the client config file in config xd, anyways client config is untouched

**Comment by Brian-Wuest** [comment]
I haven't been able to duplicate the issue, but I can see where it _might_ be happening and I am working on a fix. I am also noticing a different issue when going back and forth between Client and Server worlds, so I am working on fixing that too.

**Comment by Brian-Wuest** [comment]
This issue has been addressed, and a new version has been pushed for Fabric and NeoForge.

This new version has been uploaded to CurseForge and Modrinth.

This may take some time on the CurseForge side but should be approved shortly.

If this continues to be an issue, it may be a mod compatibility issue as I wasn't able to actually duplicate the problem but could see how it could be a problem.
