### ISSUE TITLE
End gateway

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#30]
Add a way to create a end gateway. It should be designed in a similar aesthetic as the nether gateway.

It will be unfinished so the player still have to complete it but it allows them to not have to find one in the overworld.

**Comment by IamAlathe** [comment]
I like this, as finding a stronghold can be a real pain, then sometimes, once you do, finding the portal is a whole other challenge.  Also, it is not really possible on some types of games, like skyblock.

It sounds like this would be different from other mods that add artificial or portable ender portals, as most of them (that I've seen anyway) require stuff from the end (like end stone), so you have to have gone there once already.  Perhaps your created portal blocks could require things like quartz and prismarine, for the appearance as well as a bit of difficulty.  Or dyed bits?  Seems to me you shouldn't be able to go the end at the beginning of a game 😆 (unless you're in creative, then whatever)

**Comment by Brian-Wuest** [comment]
Implemented in version 1.1.1.10 for Minecraft version 1.10.2. This will be bumped for Minecraft version 1.11.2 shortly. Closing issue.
