### ISSUE TITLE
Noticeable changes between 1.11.2 and 1.10.2 need porting

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Brian-Wuest/MC-Prefab#33]
Please port new structures to 1.10.2 until surge releases a 1.11.2 or a 2.0 release I am staying at 1.10.2.

**Comment by P3rf3ctXZer0** [comment]
https://minecraft.curseforge.com/projects/surge/files

**Comment by P3rf3ctXZer0** [comment]
I know foamfix is 1.11.2 but I also want the surge mod.

**Comment by Brian-Wuest** [comment]
I am guessing that you are referring to the fix needed for foamfix in 1.11.2? I believe that this was already ported back to 1.10.2.

Also all structures are initially released in 1.10.2 and then moved to 1.11.2

**Comment by Brian-Wuest** [comment]
I did a compare of the [StructureRenderHandler.java](MC-Prefab/src/main/java/com/wuest/prefab/Render/StructureRenderHandler.java) which is the file which was fixed when I addressed the issue for FoamFix and that file isn't different between 1.10.2 and 1.11.2's versions except for the required differences such as core names (worldObj in 1.10.2 and world in 1.11.2). 

So unless you find a specific issue with using the Surge mod I am not sure where you want to go with this.

**Comment by P3rf3ctXZer0** [comment]
Oh well in that case; carry on my wayword son; they'll be peace when you are done XD
