### ISSUE TITLE
Add new starter house options (Desert, Snowy)

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#35]
The starter house doesn't have a lot of options right now for different Biomes. The basic house is not visually appealing and the Ranch and Hobbit house only work well in temperate Biomes (plains, forests). 

The Loft style house is visually interesting but uses Nether materials and is disabled by default because of this.

We discussing adding two new types of starting houses for the Desert and Snowy biomes. This will give us some good variety and allow players to have a starting house which looks like it should be there in-case they are placed in a very large desert/snowy biome.

The Desert style will be styled like a pyramid because....deserts have pyramids :smile:. The Snowy one will be styled like an igloo.

**Comment by Brian-Wuest** [comment]
This has been implemented in version 1.1.1.11 for Minecraft 1.10.2 and 1.2.0.6 for Minecraft 1.11.2.

These are available on curseforge.

**Comment by IamAlathe** [comment]
These are really cool!  I love seeing new stuff happen in this mod!
