### ISSUE TITLE
Config option for less glowstone?

### ISSUE THREAD

**Issue by mkire** [Brian-Wuest/MC-Prefab#36]
I'd like a config option that replaces all the glowstone used by most of the buildings with the new paper lanterns. I don't really like the nether, so having to go there for stacks and stacks of glowstone blocks to use in building isn't my idea of fun.

**Comment by Brian-Wuest** [comment]
We actually wanted to change over to using the paper lanterns for most of the buildings as well (and change the recipes accordingly) when we introduced the block.

So this is perfect!

Not all buildings will change but I am sure a lot will. Need to discuss with Kaojinn which ones we want to change.

**Comment by Brian-Wuest** [comment]
This has been addressed in version 1.1.1.12 for Minecraft 1.10.2 and in version 1.2..0.7 for Minecraft 1.11.2.

These will be available on CurseForge at some point today.
