### ISSUE TITLE
Magic Temple

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#37]
There was a request for making a magic centered building.

The magic temple would have a much cooler design than the warehouse, and would be solely for enchanting and brewing.

**Comment by BrisingrAerowing** [comment]
Sounds cool.

**Comment by Brian-Wuest** [comment]
This has been in implemented in version 1.1.1.14 and 1.2.0.9 for MC version 1.10.2 and 1.11.2 respectively.
