### ISSUE TITLE
Server Welcome Center

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#41]
This is all about a creative item which will allow the server admin to create a welcome center for their players.

The basic idea is to provide a safe place for server players when they first join the server.

Tentative Plans:
Plenty of beds
Plenty of chests
A food area.
It'll look fancy!

**Comment by BrisingrAerowing** [comment]
Sounds like an interesting building. Might also be usable as an Inn as well.

**Comment by Brian-Wuest** [comment]
Released with 1.3.0.14 for MC1.12.2 and 1.2.0.18 for MC1.11.2
