### ISSUE TITLE
Villager houses builder only builds flat roof version

### ISSUE THREAD

**Issue by Ozzymud** [Brian-Wuest/MC-Prefab#42]
Prefab 1.2.0.8
Forge 12.20.0.2315 MC 1.11.2

Am able to preview all villager structures, but when clicking build with any structure selected the flat roof variant is the only one built, even with another selected. The starter house builder works as expected though. Haven't played with the mod enough yet to know if there are other builders that have a choice to which structure is built.  

Nothing is printed in the logs when I place structures, so nothing to report there.

**Comment by Brian-Wuest** [comment]
Wow, that's a pretty bad bug. Working on that now.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.1.1.14 for minecraft version 1.10.2 and version 1.2.0.9 for minecraft version 1.11.2.
