### ISSUE TITLE
[Suggestion] About the Starter House Crafting

### ISSUE THREAD

**Issue by BrisingrAerowing** [Brian-Wuest/MC-Prefab#43]
I noticed a thread about crafting the starter house, and that you couldn't figure out a good recipe for it, as it has so many variations.

How about having variations of the item that only does one type of starter house each (e.g. Ranch or Desert), and have different crafting recipes for each one. This would solve the recipe items issue.

**Comment by Brian-Wuest** [comment]
Nice, we should have thought of that ourselves a while ago.

It'll take a while since there are a total of 6 variations right now.
1. Basic
2. Ranch
3. Loft
4. Hobbit
5. Desert
6. Snowy

**Comment by BrisingrAerowing** [comment]
Sounds good.

**Comment by Brian-Wuest** [comment]
Alrighty, Kaojinn and I have been talking about this and we have a pretty good solution.

We will allow the player to craft the original item. The main difference is that it will now include any of the chest items or furnace fuel.

Recipe:
Crafting Table | Clock             | Furnace
Comp. Stone  | Bed                | Comp. Stone
Bund. Timber | Bund. Timber | Bund. Timber

This allows us to keep the original assets (GUI, Item Textures) and still implement this request.

**Comment by Brian-Wuest** [comment]
Released in versions 1.1.1.15 for MC 1.10.2 and 1.2.0.10 for MC 1.11.2.
