### ISSUE TITLE
Crashing when using OTG and BB with Prefab.

### ISSUE THREAD

**Issue by Claycorp** [Brian-Wuest/MC-Prefab#48]
See PG85/OpenTerrainGenerator#43

**Comment by Brian-Wuest** [comment]
Not sure if you linked in the wrong log file to pastebin but that exception is coming from Botania as referenced in the first line of the ArrayIndexOutOfBounds exception: vazkii.botania.common.block.mana.BlockSpreader.func_176203_a(BlockSpreader.java:87)

Prefab doesn't have any Terrain/World Generation functionality when a player is joining the world. The most we do is check if the player should get an Item when they log in.

If you re-enable Prefab and disable Botania do you still get the issue?

If you do, can you please provide a new error log for me to look at?

**Comment by Claycorp** [comment]
The issue will go away if you remove any one of the mods involved. Botania wasn't updated and OTG updated but did not break anything. It never came up till I switched some mods off for testing and turned them back on. Why Prefab is part of this I'm not sure.

I'm also not sure why it would be complaining about botania spreaders as they shouldn't generate in the world anyway. I'm going to do some more testing with just these mods to see if I can find anything else.

**Comment by Claycorp** [comment]
Well with just Botania, Biome Bundle and Prefab (with the required mods) it works fine..... Something is definitely off about this whole thing.

**Comment by Brian-Wuest** [comment]
Hmmm, not sure what to tell you on that end then. Do you still have OTG or is that a requirement of Biome Bundle? (Don't remember).

**Comment by Claycorp** [comment]
Sorry bout the late reply, just getting back to this issue again.

OTG is the mod doing all the world gen work. Biome Bundle is just the settings it follows.

**Comment by Brian-Wuest** [comment]
I am going to close this issue since this hasn't been updated in a while and appears to be an issue with other mods.
