### ISSUE TITLE
Mod crashes game on launching

### ISSUE THREAD

**Issue by jess555** [Brian-Wuest/MC-Prefab#50]
crashes back to launch screen and gives this error-The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Prefab (prefab)

**Comment by Brian-Wuest** [comment]
What version of the Mod and Minecraft. Can you post the full crash log to gist and provide a link?

This will help identify the issue and provide a quick turn around.

**Comment by jess555** [comment]
Using version 1.12 of minecraft, prefab 1.3.0.1, and forge 1.12-14.21.0.2349.  The launcher will not let me open the link for the full crash report.

**Comment by jess555** [comment]
Updated to the newest version of forge and it works! Thank you for making this mod. I love it and have been excited for the 1.12 update.  =0)

**Comment by Brian-Wuest** [comment]
I am glad that you were able to find a resolution!

Have a good one!
