### ISSUE TITLE
Compressed blocks

### ISSUE THREAD

**Issue by ArashiDragon** [Brian-Wuest/MC-Prefab#51]
There are a lot of mods that add compressed blocks (like Dirt, Cobble, etc)
Example: **[Extra Utilities](https://github.com/rwtema/extrautilities)**

> B:CompressedCobblestone=true
> B:CompressedDirt=true
> B:CompressedGravel=true
> B:CompressedNetherrack=true
> B:CompressedSand=true

Would it be possible for your mod to check the ore dictionary for compressed blocks? That way there won't be any conflict. Or some other alternative method for allowing cross-mod compatibility.

The mod: **[Quark](https://github.com/Vazkii/Quark)**
In its config has checks:

>     "charcoal block" {
>         # This feature disables itself if any of the following mods are loaded: 
>         #  - actuallyadditions
>         # This is done to prevent content overlap.
>         # You can turn this on to force the feature to be loaded even if the above mods are also loaded.
>         B:"Force Enabled"=false
>     }
> 

Love the mod but I have to choose between it and other mods if I don't use something to tweak recipes to remove conflicts. I'm no coder, so I hope I was able to explain this idea in a way that was understandable.

**Comment by Brian-Wuest** [comment]
Unfortunately the compressed blocks introduced by Extra Utilities don't exist in the Ore Dictionary. The developer is responsible for adding things to the Ore Dictionary, it's not an automatic thing. I confirmed this using the Ore Converter mod.

I could certainly add my compressed blocks to the Ore Dictionary but then the Extra Utilities developer would have to push out an update for their blocks to use the same name I did.

**Comment by ArashiDragon** [comment]
I'll go yell at Tema... Please do so, I'll see what I can do to get ExtraUtils to do the same...

**Comment by Brian-Wuest** [comment]
Since Extra Utilities has so many different levels for their compressed blocks the name would have to be something like this:

compressed[BlockName][Level]

examples:
compressedCobbleStone1
compressedCobbleStone2
compressedCobbleStone3
compressedCobbleStone4
compressedCobbleStone5
compressedCobbleStone6
compressedCobbleStone7
compressedCobbleStone8

compressedDirt1
compressedDirt2

**Comment by Brian-Wuest** [comment]
I will be releasing this change soon, if the name needs to be changed later it can be.

**Comment by Brian-Wuest** [comment]
This has been released for 1.11.2 and 1.12.
