### ISSUE TITLE
crash at statup with 1.12 forge 2443 prefab 1.3.0.2

### ISSUE THREAD

**Issue by JasonKillsUs** [Brian-Wuest/MC-Prefab#53]
i have a crash:
"https://pastebin.com/9QUD77Jg"
thanks for looking into it

**Comment by Brian-Wuest** [comment]
Thank you. I will be looking into this.

**Comment by Brian-Wuest** [comment]
I was able to duplicate this and found out the issue.

I needed to clean out my development environment which is why I could not duplicate locally.

This has been addressed with version 1.3.0.3 which has been released onto CurseForge.

Thank you!
