### ISSUE TITLE
crash in 1.12_2433/1.3.0.3 

### ISSUE THREAD

**Issue by JasonKillsUs** [Brian-Wuest/MC-Prefab#54]
after placing the Moderate House in a different Village:

"https://pastebin.com/YDDdHbka"

thanks

**Comment by JasonKillsUs** [comment]
it seems it´s the "spruce house" the second "acacia" works fine

**Comment by Brian-Wuest** [comment]
Sigh....Minecraft always breaking stuff.

I will look at this when I get home. Wouldn't have thought that they would have changed the Jukebox.

**Comment by Brian-Wuest** [comment]
Hello Jason, I tried duplicating this in 1.12 in a development environment and in a non-development environment where I ran this in the normal minecraft game. I also ran this in a server and was still unable to duplicate this issue.

That being said, I was testing with only my mod in those circumstances and I noticed that you were running a lot of mods.

Are you able to place a Jukebox normally? If you are, can you remove mods until the building generates normally?

I will leave this issue open for a few days to give you time to test this out.

Thank you!

**Comment by JasonKillsUs** [comment]
yes you nailed it, thanks a ton :-), made a new world and everything works just as suppose to be.
Thank you very much for your time and effort.
