### ISSUE TITLE
Greenhouse Lighting Issue

### ISSUE THREAD

**Issue by BrisingrAerowing** [Brian-Wuest/MC-Prefab#56]
On the middle strip of farmland in the greenhouse, in between the lights, there are some spots that aren't getting enough light to sustain plants, causing them to pop off when they get an update.

**Comment by Brian-Wuest** [comment]
Thanks for the report, I will try to duplicate this issue and figure out how to address it.

**Comment by Brian-Wuest** [comment]
I was able to duplicate this issue. I am adding more lamps. This will be address in 1.11.2 and above.

**Comment by Brian-Wuest** [comment]
This has been addressed for 1.11.2 and 1.12 and has been pushed to curse forge.

**Comment by BrisingrAerowing** [comment]
Great!
