### ISSUE TITLE
[Feature] Moderate Houses Customization

### ISSUE THREAD

**Issue by BrisingrAerowing** [Brian-Wuest/MC-Prefab#57]
Is customization for the Moderate Houses planned? Like removing the Mineshaft / Chests / Items / Etc?

**Comment by Brian-Wuest** [comment]
We add it if its needed. We weren't planning on it unless requested.

Are you using this as your initial house and don't want some items/blocks?

**Comment by BrisingrAerowing** [comment]
At the time I wasn't using the mineshaft, but I have started using it by turning it into a high tech bunker of sorts, where a lot of machines (and control systems) go. I also play in creative, so I don't really need the furnaces or chests, as I usually replace them with things like the furnace from Extra Utilities 2 and Refined Storage setups.

**Comment by Brian-Wuest** [comment]
I am glad that you have found some use for it.

I can look at adding some checkboxes for the chests, mineshaft and chest item.

Might be a while until this get's implemented though. We are trying to get Repurpose up to snuff in terms of code and the curse page.

**Comment by Brian-Wuest** [comment]
The following options were made available and have been released to curse forge.
Add Chests
Add Chest Contents
Add Mineshaft

They are defaulted to true.

Thank you!
