### ISSUE TITLE
certain structures are not craftable

### ISSUE THREAD

**Issue by lawfulrocky** [Brian-Wuest/MC-Prefab#60]
the ender gate way aqua base  machinery tower and barn is not craftable in 1.11.2

**Comment by Brian-Wuest** [comment]
What version of forge are you using?

**Comment by Brian-Wuest** [comment]
What version of the mod are you running?

Also, please check your configuration file to make sure that the recipes aren't disabled. They *should* be enabled by default unless you accidentally disabled them or if you're playing a modpack and the modpack developer disabled them.

You can see if they are disabled or not by going to the Mod Config in the Main menu.

Mod Options -> Prefab -> Recipes
On this screen is where all of the recipes can be disabled/enabled.

**Comment by Brian-Wuest** [comment]
Closing as requested information has not been provided.

This issue can be re-opened if additional information is provided to assist with troubleshooting.
