### ISSUE TITLE
Feature request - Block safe config option.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#61]
I would love to see a config option that would not allow you to spawn in a structure unless it did not damage any blocks.

This is an example why this is needed- Twilight forest dungeon, bedrock bypassed by the structure.

![2017-08-30_21 36 51](https://user-images.githubusercontent.com/4427684/29905441-02ff11a4-8dcc-11e7-89eb-92aca740de5e.png)

Not to mention the griefing potential.

**Comment by Brian-Wuest** [comment]
We actually have had something for this for a long time. Maybe not specifically so the player cannot destroy bedrock though.

If a block is protected by something like FTBUtilities or some other mechanism the player will get a chat message stating as such. 

Please see this wiki page and see if this is what you expect.

https://github.com/Brian-Wuest/MC-Prefab/wiki/Anti-Griefing

**Comment by Brian-Wuest** [comment]
I have pushed an update that checks if there are unbreakabke blocks in the build space. If there are any, the user will get a message and the building will not spawn.

The new release is on curseforge for 1.11.2 and 1.12.

Thanks!

**Comment by ProsperCraft** [comment]
Thank you!
