### ISSUE TITLE
Feature request - Ability to have a safe placement mode- no blocks broken but grass/dirt.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#62]
I just had a player use his starter house to get enough obsidian to make a nether portal.

Please add a config option to block placement if it will break anything but grass/dirt? or make the blocks allowed to break configurable?

**Comment by Brian-Wuest** [comment]
This could be very tricky. Maybe check the material of the block being broken instead of particular blocks. This way its easier to code and should satisfy this need.

How did they get obsidian right away? They should still have to mine it up unless it was retrieved from the mineshaft which is the other issue.

**Comment by ProsperCraft** [comment]
overworld obsidian in my pack, they place the house, and get a bunch of it.

**Comment by Brian-Wuest** [comment]
Since the buildings replace blocks with air before placing the house blocks the only thing causing this to occur would be the mineshaft. So I am still confused as to how they get the blocks into their inventory to build the nether portal.

**Comment by Brian-Wuest** [comment]
Please provide more information about how the player was able to obtain obsidian so quickly as I am not sure how they could have. I also could not find a mod called "Overworld Obsidian"

**Comment by ProsperCraft** [comment]
The  mod dooglamoo worlds adds giant volcanoes made of obsidian with lava in them

**Comment by Brian-Wuest** [comment]
So it sounds like the player used the house yo break the obsidian to get to the lava and then used water to make the portal frame and then some flint and steel to generate the portal?

**Comment by Brian-Wuest** [comment]
I think I have an idea of how they got the obsidian. They must have gotten it from their mineshaft since that would have been the only way to get it into an inventory without having access to diamond tools. 

With the new config option of not filling up the chest is this issue necessary anymore?

**Comment by ProsperCraft** [comment]
Will no longer be an issue, thank you.
