### ISSUE TITLE
Feature Request- Disable ores chest at the bottom of the ladder.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#63]
Currently when the house is placed, all blocks broken when the ladder is formed get placed in a chest in the bottom of the stairs, breaking progression, please add a config option to disable that chest?

**Comment by Brian-Wuest** [comment]
You should already be able to do this by not allowing chests to begin with. Think thats done in the house generation restrictions option.

**Comment by ProsperCraft** [comment]
I do want the starter kit chests, just not the ore chest at the bottom of the stairs.

**Comment by Brian-Wuest** [comment]
I could add an option for that.

**Comment by Brian-Wuest** [comment]
This has been released with version 1.2.0.15 for MC 1.11.2 and version 1.3.0.9 for MC 1.12.0/1.12.1.

Closing issue.
