### ISSUE TITLE
Pre-fab incapability with ALL the Mods 3 

### ISSUE THREAD

**Issue by LordRavenShadow** [Brian-Wuest/MC-Prefab#65]
the version im on is prefab-1.3.0.11.jar for minecraft 1.12.x the only thing thats working is the starter house, no other buildings are working :), just a heads up.
and every time you try to preview a building it would crash minecraft.

**Comment by Brian-Wuest** [comment]
Thanks for the heads up. Wasn't aware we were in that one yet. I will take a look.

**Comment by Brian-Wuest** [comment]
This appears to come from the mod "Plants" I have a fix for what that mod does to the game and am testing against AllTheMods 3 again to make sure I didn't miss anything.

**Comment by Brian-Wuest** [comment]
This has been fixed with 1.3.0.12 which is now available on CurseForge.

**Comment by LordRavenShadow** [comment]
thank you for responding so fast
