### ISSUE TITLE
Phasic Block Issue

### ISSUE THREAD

**Issue by JDBS** [Brian-Wuest/MC-Prefab#66]
MC-Prefab version: 1.3.0.11 & 1.3.0.12
MC-Forge version: 14.23.0.2501

Phasic block collapses tick system when it receives a redstone signal. That issue freezes the game.

**Comment by Brian-Wuest** [comment]
Can you describe your physic block layout or was it just one block?

**Comment by Brian-Wuest** [comment]
Nevermind, I duplicated the issue. That's a bad one too. 

I was able to duplicate this in 1.11.2 so I will be starting there.

Thank you for reporting this!

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.3.0.13 for Minecraft Version 1.12.2.

Thank you!
