### ISSUE TITLE
Config Options to block certain items in starting house blueprint

### ISSUE THREAD

**Issue by Davoleo** [Brian-Wuest/MC-Prefab#71]
1. What version of Minecraft and forge are you running?
1.12.2

1. What version of the mod are you running? 
1.3.0.13

Config Options to enable and disable starting house blueprint config section 
![Screenshot](https://user-images.githubusercontent.com/24458276/34528108-1fe39c7e-f0a8-11e7-82be-1c9b284c028d.PNG)

1. Are you running a specific modpack on CurseForge that I can use to test it out? Personal modpacks and modpacks from other distribution sites are hard for me to test with:
ImmersiveCraft (MK), 1.4/1.5 DEV
In 1.4 PreFab may not be on the latest version, but latest or not latest the issue is the same

**Comment by Brian-Wuest** [comment]
There are already options for this, though probably not very inuitive or well implemented.

The way it is right now is that the config options will prevent the house items from generating but I did not remove them from the screen.

I can update the screen to do this. I am currently working on a pretty big update, but I can include this in the next release.

Thanks!

**Comment by Davoleo** [comment]
No problem :)
Yeah, I don't know if I explained myself well, but, as a modpack developer, I disabled the default vanilla furnace recipe and I noticed that in the starting house blueprint you're able to put a furnace in your house, so yeah, I would like to disable the option to put a furnace in the house
I hope my english wasn't too bad :P

**Comment by Brian-Wuest** [comment]
Yes you were fine, this actually allows me to clear up some of the configuration options which have been in there for a while. For example there is currently the "Enable House Generation Restrictions" which removes the crafting table, furnace and chests from the starting house. 

This was originally intended for a TSON craft user. That single configuration option is a little heavy handed if you want to only disable one of those 3 items. So I am breaking things out to give modpack developers more control about what exactly is included/excluded from the building.

**Comment by Brian-Wuest** [comment]
Released with 1.3.0.14 for MC1.12.2
