### ISSUE TITLE
Remove structure orientation button from structure GUIs

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#73]
This button was added a long time ago when the starter house was added to WuestUtilities. Now the button just seems confusing to myself and others since you have to choose the opposite direction to where you are facing. 

This button will be removed from ALL structure screens and the structure will always be facing the player/built in the direction the player is facing. This way someone doesn't accidentally build the structure behind them or to their left/right.

This will also allow me to do the first step of the customization structure issue (#68).

**Comment by Brian-Wuest** [comment]
Released with 1.3.0.14

**Comment by IamAlathe** [comment]
I'm forever mis-reading my map and placing my structures the wrong way.  This is a great change. 😸

**Comment by Brian-Wuest** [comment]
I'm glad you like it. It's also something that's been bugging me for a while.
