### ISSUE TITLE
File Missing 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Brian-Wuest/MC-Prefab#75]
https://minecraft.curseforge.com/projects/prefab/files/2525279
![2018-01-28 10_17_30-not found - minecraft curseforge](https://user-images.githubusercontent.com/10351221/35485425-7b1c0570-0414-11e8-83a9-9badfa1d04d2.png)

**Comment by Brian-Wuest** [comment]
Can't tell what file you were trying to access. If it's the new one, I can get to it no problem and I didn't archive anything today.

**Comment by Brian-Wuest** [comment]
Not an issue. Using the link provided directs to a good web page on CurseForge.
