### ISSUE TITLE
Prefabs bypass protected blocks.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#79]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.12.2
    1. Forge Version: forge-1.12.2-14.23.2.2628-universal
    1. Mod Version:prefab-1.3.0.17
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)

1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

https://minecraft.curseforge.com/projects/futurepack
Futurepack adds dungeons that are protected and you can't bypass the dungeon by digging blocks, not even in creative.    The mineshaft from the prefab houses and the bulldozer don't' check against this protection, and break all of the blocks and allow players to cheat the dungeon which bypasses a ton of obstacles they are supposed to do before they get the rewards.

**Comment by Brian-Wuest** [comment]
What mod specifically adds these dungeons?

I already have code to check for protected spaces which I know the bulldozer checks for.

The code it uses can be found here:
https://github.com/Brian-Wuest/MC-Prefab/blob/b407c7628679dc52584aae29516e0f5355ae1db2/src/main/java/com/wuest/prefab/BuildingMethods.java#L499

I don't think the mineshaft checks properly for this, if you're on a server in the mean-time you can turn the mineshaft option off. It's in the starter house configuration.

**Comment by ProsperCraft** [comment]
The mod I linked above - Futurepack.

it's the bulldozer that poses the greatest problem.

**Comment by mcenderdragon** [comment]
Is the Bulldozer sending BreakBLock Events ?

**Comment by Brian-Wuest** [comment]
@mcenderdragon, yes all of my structure items send this event for every block in the space it will clear out before building the structure. This is done server-side.

Below is the trace of where the method is called.
https://github.com/Brian-Wuest/MC-Prefab/blob/b407c7628679dc52584aae29516e0f5355ae1db2/src/main/java/com/wuest/prefab/Proxy/Messages/Handlers/StructureHandler.java#L42

https://github.com/Brian-Wuest/MC-Prefab/blob/b407c7628679dc52584aae29516e0f5355ae1db2/src/main/java/com/wuest/prefab/Config/Structures/StructureConfiguration.java#L135

https://github.com/Brian-Wuest/MC-Prefab/blob/b407c7628679dc52584aae29516e0f5355ae1db2/src/main/java/com/wuest/prefab/Config/Structures/BulldozerConfiguration.java#L54

https://github.com/Brian-Wuest/MC-Prefab/blob/b407c7628679dc52584aae29516e0f5355ae1db2/src/main/java/com/wuest/prefab/StructureGen/Structure.java#L400

https://github.com/Brian-Wuest/MC-Prefab/blob/b407c7628679dc52584aae29516e0f5355ae1db2/src/main/java/com/wuest/prefab/BuildingMethods.java#L499

**Comment by mcenderdragon** [comment]
This looks like it should work fine. The structures are they build while generating the world of afterwards by players ?

**Comment by Brian-Wuest** [comment]
They are built afterwards by players.

**Comment by mcenderdragon** [comment]
@ProsperCraft have the players checked if they could break the dungeon from hand ? Or are they unable to break the dungeon but the bulldozer is able to do so ?

**Comment by ProsperCraft** [comment]
It was protected, it is still protected.

![2018-04-08_21 03 59](https://user-images.githubusercontent.com/4427684/38477536-64eb1b18-3b70-11e8-88e5-10c22f8b075e.png)

**Comment by mcenderdragon** [comment]
this means your are not allowed to build blocks in the area where previously the dungeon was ?

**Comment by Brian-Wuest** [comment]
I just created a test world in my development area and I was not able to duplicate this. I have not changed how this process works on my end. This was in single player mode and dedicated server mode using default configuration settings for FuturePack.

I found an above ground structure which I could not break by hand and properly got he message from Prefab saying that the building could not be placed due to protected areas/blocks.

The interesting thing I did notice is that the block itself it not protected. In creative I can place a Purple Colored Metal Block and break it by hand. But if I try to do this for the structure it is immediately replaced. Maybe there is an issue with this particular structure's protection detection?

Single Player Mode
![2018-04-09_05 21 01](https://user-images.githubusercontent.com/13502068/38492944-1ad085d6-3bb6-11e8-9854-2ea3af9598e4.png)

Dedicated Server
![2018-04-09_05 36 30](https://user-images.githubusercontent.com/13502068/38493499-098c1eaa-3bb8-11e8-9028-1c0ceb3af6ed.png)

**Comment by mcenderdragon** [comment]
From the pictures above the Bulldozer is a moving blockbreaking structure right? is it possible it can move into an dungeon an breaks it ? For the protection is am listening to the BlockBreakEvent.

**Comment by Brian-Wuest** [comment]
It's not really a structure, it just clears 16x16 area by setting all of the blocks to air. Of course this still occurs after I verify that there are no protected blocks in range. BlockBreakEvents are not called except for the initial check.

Something I noticed in ProspercCraft picture is that it looks like it sheared off the roof of the dungeon. After work I will see if i am not going down far enough for this check.

**Comment by Brian-Wuest** [comment]
I just double checked the situation where the bulldozer was used on a block was at the same level as protected blocks. It worked properly and did not destroy protected blocks. I also went 1 block down from the top of a structure and tried to clear and I got my message about protected blocks.

![2018-04-10_16 44 57](https://user-images.githubusercontent.com/13502068/38585482-ae2b6a1a-3cdf-11e8-8982-753f04e52b1c.png)

![2018-04-10_16 50 44](https://user-images.githubusercontent.com/13502068/38585493-b0d76caa-3cdf-11e8-92ca-e3dddac7df0e.png)

**Comment by mcenderdragon** [comment]
Is Sponge Hacking into the forge Event Bus ? If so it would explain why we cant reporoduce this.

**Comment by Brian-Wuest** [comment]
That could be. I have never used Sponge and I don't support it.

**Comment by mcenderdragon** [comment]
Yeah sponge is always very messy...

**Comment by Brian-Wuest** [comment]
@ProsperCraft Do you have sponge on your server? If you do, does this issue still come up if you remove sponge?

**Comment by Brian-Wuest** [comment]
Since there has been no response to the request for more information for this issue in 2 weeks, I am closing this issue.

This issue can be re-opened if there is more information provided.

**Comment by ProsperCraft** [comment]
Sorry, I missed a notification, yes, we have sponge enabled on the server.

**Comment by Brian-Wuest** [comment]
Sponge-enabled servers are not supported with this mod. Sponge has caused issues in the past with Prefab and specifically around this issue of bypassing the block protections.

See issue #20 for an example.
