### ISSUE TITLE
Prefab schematics include ores.

### ISSUE THREAD

**Issue by ProsperCraft** [Brian-Wuest/MC-Prefab#80]
It might be helpful to some to clean up the schematics to not include ores, for example in the case of hardcore packs.

It isn't an issue in my pack, it just confused players because they dug out their basement and found ores, but we have oregen disabled in the overworld.

**Comment by Brian-Wuest** [comment]
which ones did you notice had ores in them? As far as I remember, only the Acacia Moderate House had them.

**Comment by ProsperCraft** [comment]
Acacia yes, and the welcome center, which isn't that big of a deal.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.3.0.19 which is now available on curse forge.

Thank you!
