### ISSUE TITLE
Not built against latest forge.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Brian-Wuest/MC-Prefab#81]
Fix forge Build Against this is Lex Manos Current Recommended Version
Download Recommended
1.12.2 - 14.23.3.2655

https://files.minecraftforge.net/

Surprisingly you are recommending a beta forge.

Forge version 1.12.2 - 14.23.2.2641 is recommended for this mod.

Dev Build

14.23.2.2641 | 03/30/18 05:47 AM
-- | --

**Comment by Brian-Wuest** [comment]
I have verified that the latest release of Prefab works with the recommended build of Forge.

The comment has been updated.

Thanks!

**Comment by P3rf3ctXZer0** [comment]
No Problem :D
