### ISSUE TITLE
1.12 Crash with SteamAgeRevolution

### ISSUE THREAD

**Issue by Zygus42** [Brian-Wuest/MC-Prefab#84]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version: 1.12.2
    1. Forge Version: forge-1.12.2-14.23.3.2673-installer-win
    1. Mod Version: prefab-1.3.0.20
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

[crash-2018-05-05_12.16.53-server.txt](https://github.com/Brian-Wuest/MC-Prefab/files/1976346/crash-2018-05-05_12.16.53-server.txt)

When the mineshaft dug the tunnel down, got this crash.  Looks like a conflict with some block from either:
SteamAgeRevolution-1.12.2-0.2.0
https://minecraft.curseforge.com/projects/steamagerevolution

or it's core mod:
base-1.12-3.4.2
https://minecraft.curseforge.com/projects/base

Further examination shows it to be Sulphur Ore, which when picked with a diamond pickaxe drops nothing at all.  It ought to drop Sulphur dust.  I will report the mining issue to that mod's creator(s) as well.

**Comment by Zygus42** [comment]
Oops, didn't realise I didn't have the latest version of steam age revolution:
SteamAgeRevolution-1.12.2-0.2.2
base-1.12.2-3.7.1

Same problem persists though.

**Comment by warlordjones** [comment]
Huh. Weird. I'll pass this along.

**Comment by Brian-Wuest** [comment]
I am closing this issue as it is being tracked by the B.A.S.E mod team.
