### ISSUE TITLE
New sea structures for 1.13

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#88]
Edit: Credit goes to FavouriteDragon on CurseForge for the idea.

This won't be done for a while but for documentation purposes we will add some ocean/underwater specific buildings which have been suggested.

**Sea Turrets**
- Contains Conduits and enough prismarine so that it hunts for mobs

**Aqua Base Upgrade**
- Adds more content, and a conduit.

**A shipwreck house**

**Comment by IamAlathe** [comment]
I'm excited that y'all are looking ahead.  1.13 is bringing interesting content, and I'm glad to see you making sure it doesn't go to waste. ;)

**Comment by Brian-Wuest** [comment]
Closing as the SubAquatic house and aqua base upgrade are now available.
