### ISSUE TITLE
Starter House not appearing in inventory on a fresh start

### ISSUE THREAD

**Issue by Herekar** [Brian-Wuest/MC-Prefab#91]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version:1.12.2
    1. Forge Version:14.23.4.2708
    1. Mod Version:1.3.0.22
1. What type of issue is this? Choose one of the following:
    **Bug**
 
I noticed after updating this mod and doing a test run of my modpack that the starter house isn't showing in the inventory so i got poking around and found there is a typo in the config file i fixed mine easy enough but just wanted to give you a heads up here is how it appears..
# Determines which starting item a player gets on first world join. Server configuration overrides client. [default: Starting House]
        S:"Starting Item"=Starting Hosue

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.3.0.23 which is now available on curseforge. 

Thanks!
