### ISSUE TITLE
Some new ideas

### ISSUE THREAD

**Issue by GrzechuGrek** [Brian-Wuest/MC-Prefab#94]
1. Luxury houses/residens
Since there is some basic and moderate houses, then I think why not a luxury houses?
Such houses can to be spacious, decorative, to has few floors, more rooms as well. Also alchemy/library workshop. etc. 
Around building can be a good looking square like a parks, gardens etc.
Of course such building should be a very expensive to craft.

2. City style buildings such as towers, skyscrapers, block of flats, offices buildings etc.
Rather for "city look" than to live in. There can to be a lot options like a kind of building, his pattern, size(especially number of floors) and kind of materials.
There is don't have to crafting since this is prefered for mapmakers, but if is nessesary, there can be a way to craft it.

3. Buildings for servers use, such a shops, pvp arena and spleef arena.

**Comment by Brian-Wuest** [comment]
I really like these ideas! We will work on them when we can. We have been very busy with work and house projects.

If you or anyone else for that matter are feeling creative we can accept worlds through thinks like dropbox or drive but there are some restrictions.

1. You must use vanilla blocks. If you think you need a custom block for the design let us know and we can create that too.
2. We reserve the right to change the design as necessary for balance or aesthetics.
3. If you want, you will be credited for contributions on the curseforge page.

I will probably post this out onto curseforge as well.

**Comment by Hir0shiyt** [comment]
Hey Brian i want to help translating the mod to my language, can i?

**Comment by Brian-Wuest** [comment]
This mod is translated to a number of different languages. Which one do you require?

I am a native English speaker and nothing else (typical American). Any translations that I have done were done through Google Translate. Other folks have provided translations for their languages and have verified as best I can through Google Translate.

**Comment by Brian-Wuest** [comment]
Closing this issue. If there are more suggestions please talk about them with the rest of the community on our discord server!
