### ISSUE TITLE
my chest don't open

### ISSUE THREAD

**Issue by thep1001** [Brian-Wuest/MC-Prefab#96]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version:1.12.2
    1. Forge Version: idk
    1. Mod Version: latest
1. What type of issue is this? Choose one of the following:
    1. **Bug** when I try to open any chest it doesn't open (the ender chest crashes my game)
   
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details:
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

**Comment by Brian-Wuest** [comment]
This mod doesn't do anything with chests aside from providing them in prefabs.

Can you go into creative mode and place an ender chest? If so does opening it cause a crash? If so I need the crash log.

**Comment by Brian-Wuest** [comment]
Closing since there has been no additional information.
