### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by Notlucky101** [Brian-Wuest/MC-Prefab#98]
1. What version of Minecraft, Forge and Mod are you running?
    1. Minecraft Version:
    1. Forge Version:
    1. Mod Version:
1. What type of issue is this? Choose one of the following:
    1. **Bug** (Something doesn't work the way you expect or the game crashes/has an issue)
    1. **Enhancement** (Add/Change something)
1. If this is an **enhancement**, please provide as much detail as possible for what you would like to see changed or added. This will reduce the amount of questions we have later and provides you with what you need.
    1. Details:
1. If this is a **bug**, please provide as much detail as possible for the issue that you are running into. If possible post a log file to PasteBin or another similar site.

**Comment by Notlucky101** [comment]
Minecraft 1.22
Recipe conflict with Extra Utilities
Can you be compatible with the extra Utilities compression ? I have a mod that helps with recipe conflicts but does not alway work with your mod.

**Comment by Brian-Wuest** [comment]
My compression blocks are in the Ore Dictionary. There was a request for this previously and I have done my part. Extra Utilities has to either use my Ore Dictionary registrations or open a discussion on what the values should be and neither action has occurred yet.

Please reach out to them if you need this compatibility.

**Comment by Notlucky101** [comment]
I will do that, I was not sure who to contact. thx

**Comment by Brian-Wuest** [comment]
No problem, closing issue
