### ISSUE TITLE
Some more ideas

### ISSUE THREAD

**Issue by Brian-Wuest** [Brian-Wuest/MC-Prefab#99]
These ideas are taken verbatim from a private message from mganeta on CurseForge

1. A fancy-ish modern house made of sandstone, quartz, glass and terracotta blocks. Equipped with a swimming pool, big bedroom, fancy mine entrance and a few chests and shulker boxes full of random or not stuff. For players who don't like to get too tired ;)

 

2. A small farm for beginner farmer - including ready farm field of moderate size (with a scarecrow!) and a mini barn. Could have different seeds and farm animals eggs in a chest as a bonus.

 

3. Moderate size, nice looking castle with banners and stuff - but functional as living quarters.

 

4. Firework launcher!

 

5. One story house with a few variants of materials for blocks and glass panes  to choose from + some chests with basic/random equipment BUT with a big mine entrance hidden in the basement and and actual mine shaft with wooden floors, scaffolding and what not. Could have a few chests already full of what the mine has "gathered" during construction ;)

 

6. Wool farm. Nice cottage house + a farm for sheep + chests with shears and what not, could have dyes and some colorful wool in the chests already.

 

7. HELL entrance. Basically, a giant hole in the ground with unusual spectacle of caves full of lava, magma and nether blocks. Mob spawners, of course! The deeper, the worse it gets and some big reward in a chest at level 1 ;d

 

8. Super tall, alien looking tower, going maximum height, with elytra at the very top :)

 

9. Hoarders hut with a dozen of dogs (tamed wolves ;))

 

10. Sneaky maze with traps and mob spawners - including neutral mobs that could step at a wrong pressure plate at a wrong time! Partially made of glass blocks and glowstone to add weirdness to it

 

11. Blacksmith's house and workshop, partially/fully equipped.

12. Moderate Snowy house.

**Comment by Brian-Wuest** [comment]
Multi-level Mega Warehouse

Storage Silos

**Comment by EnterFor** [comment]
Can you add a switch to determine if the player can synthesize?
I wanted to use it on the server, but I didn't want the player to use it because it would destroy the player's existing base

**Comment by Brian-Wuest** [comment]
Synthesize what?

The server admin can turn off all of the recipes if they want too.

**Comment by zzn924418** [comment]
Hello, I designed another Moderate Houses based on Acacia House.
It has a compact main house, a sophisticated attic, a roofed corral and a smaller basement.
This is a map archive.
https://drive.google.com/drive/folders/1fy9FbkzI51-1b7U4c_7zAcKhkCSun41b?usp=sharing

**Comment by Brian-Wuest** [comment]
@zzn924418 - Thank you! We will take a look at it.

We are in the middle of a big update for the 1.12.2 version of the mod at the moment but this will be discussed!

**Comment by Brian-Wuest** [comment]
Closing this issue. If there are more suggestions please talk about them with the rest of the community on our discord server!
